### PR TITLE
Integrated new MvxUIActivityIndicatorViewHiddenTargetBinding from munkii.

### PR DESCRIPTION
**Pull request by lothrop**
Integrated the new binding from @munkii. See #1163.

### CODE REVIEW

**Comment by lothrop** [comment]
Any objections?

**Comment by martijn00** [comment]
Nope.

**Comment by martijn00** [comment]
Thanks both @lothrop and @munkii !

**Comment by munkii** [comment]
Thanks @lothrop for finishing the job

**Pull request merged**
