### PR TITLE
Adding Uno Support

### PR DESCRIPTION
**Pull request by nickrandolph**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature - Adds support for Uno

### :arrow_heading_down: What is the current behavior?
No support for Uno

### :new: What is the new behavior (if this is a feature change)?
Additional libraries MvvmCross.Uno and MvvmCross.Uno.Plugins to support Uno

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Run the sample Uno projects

### :thinking: Checklist before submitting

- [ X ] All projects build
- [ X ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [ X ] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
@Cheesebaron can you let me know what I need to do in order to generate nuget packages for MvvmCross.Uno and MvvmCross.Uno.Plugins?

**Comment by MartinZikmund** [comment]
Hi, what is the status of this PR? Anything I could help with to get it done 🙂 ?

**Comment by nickrandolph** [comment]
@MartinZikmund  I just rebased the branch. I need to test it again to make sure it's all working and I need some guidance from @Cheesebaron as to what we need to do to generate nuget packages.

**Comment by Cheesebaron** [comment]
To generate NuGet packages, the only thing that should be necessary is to use MSBuild.Sdk.Extras for the project file.

```xml
<Project Sdk="MSBuild.Sdk.Extras">
```

Additionally it needs to fulfill these conditions:

```xml
<GeneratePackageOnBuild Condition=" '$(Configuration)' == 'Release' and '$(IsTestProject)' != 'true'">true</GeneratePackageOnBuild>
```

So built in Release mode and not have "Test" in the project name.

**Comment by MartinZikmund** [comment]
Hi, is this close to release 😊 ? I had several people asking about MvvmCross support 😉 . I am happy to help if something is missing/not working yet

**Comment by Cheesebaron** [comment]
@MartinZikmund Except for it not building, then I guess it is not far from it.

I will be working on MvvmCross this week. So I'll give this one a spin and perhaps fix it up so we can get it out with 7.0.0

**Comment by MartinZikmund** [comment]
Thanks a ton 👌👌👌

**Comment by MartinZikmund** [comment]
I am trying out the current version with Uno, I am currently facing a weird problem with `x:Bind`. Consider the following code-behind:

        public MainView()
        {
            this.InitializeComponent();
            DataContextChanged += MainPage_DataContextChanged;
        }

        private void MainPage_DataContextChanged(DependencyObject sender, DataContextChangedEventArgs args)
        {
            Text = "In data context changed";
        }

        protected override void OnNavigatedTo(NavigationEventArgs e)
        {            
            base.OnNavigatedTo(e);            
            DataContext = "test";
        }

        public string Text { get; set; }

And following XAML:

```
<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
	<TextBlock Text="{x:Bind Text}" Margin="20" FontSize="30" />
</Grid>
```

In UWP this properly shows "In data context changed", but on Uno platforms it does not. It seems like the bind occurs before the `DataContextChanged` is processed or something similar. Weirdly enough, this does work with a plain Uno Platform project, only happens when the page derives from `MvxWindowsPage`.

**Comment by Cheesebaron** [comment]
@nickrandolph I've tried to get Android to build today. I can't seem to get it to work, since it generates some code behind looking like this:

```csharp
#if __ANDROID__
		/// <summary>
		/// Native constructor, do not use explicitly.
		/// </summary>
		/// <remarks>
		/// Used by the Xamarin Runtime to materialize native 
		/// objects that may have been collected in the managed world.
		/// </remarks>
		public SplitMasterView(IntPtr javaReference, global::Android.Runtime.JniHandleOwnership transfer) : base (javaReference, transfer) { }
#endif
```

The base class is MvxWindowsPage, it which inherits from Windows.UI.Xaml.Controls.Page, this type doesn't have that ctor.

The only thing I did was to bump uno to latest stable 2.4.0 and use `Uno.Wasm.Bootstrap.DevServer` instead of the CLI tool in the Wasm project, as it was throwing build errors.

**Comment by Cheesebaron** [comment]
Wasm seems to work OK.

**Comment by Cheesebaron** [comment]
Can't seem to get UWP running either.

```
4>"C:\git\MvvmCross\Projects\Playground\Playground.Uno\Playground.Uno.UWP\Playground.Uno.UWP.csproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->
4>(MarkupCompilePass1 target) -> 
4>  C:\git\MvvmCross\Projects\Playground\Playground.Uno\Playground.Uno.Shared\Views\SecondChildView.xaml : Xaml Internal Error error WMC9999: Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null.
4>  C:\git\MvvmCross\Projects\Playground\Playground.Uno\Playground.Uno.Shared\Views\SplitMasterView.xaml : Xaml Internal Error error WMC9999: Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null.
4>  C:\git\MvvmCross\Projects\Playground\Playground.Uno\Playground.Uno.Shared\Views\SplitRootView.xaml : Xaml Internal Error error WMC9999: Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null.
```

**Comment by Cheesebaron** [comment]
@nickrandolph still seems to fail to build due to: https://github.com/unoplatform/uno/issues/2937

**Comment by nickrandolph** [comment]
@Cheesebaron I've adjusted references etc and I think we should be all good now. I'd checked in the developer override which was limiting target frameworks to just android + uwp. 
I've tested droid, uwp and wasm, and they all run for me. Can you give ios a go and verify that it runs.

**Comment by Cheesebaron** [comment]
```
"D:\a\1\s\MvvmCross.sln" (Build target) (1) ->
"D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.iOS\Playground.Uno.iOS.csproj" (default target) (53) ->
(ResolveAssemblyReferences target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.iOS\Playground.Uno.iOS.csproj]
"D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.Core\Playground.Uno.Core.csproj" (default target) (50:2) ->
"D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj" (default target) (49:4) ->
  MSBUILD : error : Project has no references. [D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj]
  MSBUILD : error : Failed to analyze project file [D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj], the targets [Microsoft.Build.Execution.TargetResult] failed to execute.This may be due to an invalid path, such as $(SolutionDir) being used in the csproj; try using relative paths instead.This may also be related to a missing default configuration directive. Refer to the Uno.SourceGenerator Readme.md file for more details. [D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj]


"D:\a\1\s\MvvmCross.sln" (Build target) (1) ->
"D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.UWP\Playground.Uno.UWP.csproj" (default target) (48) ->
(_ValidateAppxPackage target) -> 
  Package.appxmanifest(36,9): error APPX1619: App manifest references the square 150x150 logo image 'Assets\Square150x150Logo.png' which does not have valid dimensions. It must be 150x150 pixels. [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.UWP\Playground.Uno.UWP.csproj]
  Package.appxmanifest(40,26): error APPX1619: App manifest references the wide 310x150 logo image 'Assets\Wide310x150Logo.png' which does not have valid dimensions. It must be 310x150 pixels. [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.UWP\Playground.Uno.UWP.csproj]
  Package.appxmanifest(37,9): error APPX1619: App manifest references the small logo image 'Assets\Square44x44Logo.png' which does not have valid dimensions. It must be 44x44 pixels. [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.UWP\Playground.Uno.UWP.csproj]
  Package.appxmanifest(41,27): error APPX1619: App manifest references the splash screen image 'Assets\SplashScreen.png' which does not have valid dimensions. It must be 620x300 pixels. [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.UWP\Playground.Uno.UWP.csproj]


"D:\a\1\s\MvvmCross.sln" (Build target) (1) ->
"D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj" (default target) (49:10) ->
"D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj" (Build target) (49:18) ->
(_UnoSourceGenerator target) -> 
  MSBUILD : error : Project has no references. [D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj]
  MSBUILD : error : Failed to analyze project file [D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj], the targets [Microsoft.Build.Execution.TargetResult] failed to execute.This may be due to an invalid path, such as $(SolutionDir) being used in the csproj; try using relative paths instead.This may also be related to a missing default configuration directive. Refer to the Uno.SourceGenerator Readme.md file for more details. [D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj]


"D:\a\1\s\MvvmCross.sln" (Build target) (1) ->
"D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj" (default target) (49:10) ->
"D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj" (Build target) (49:19) ->
  MSBUILD : error : Project has no references. [D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj]
  MSBUILD : error : Failed to analyze project file [D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj], the targets [Microsoft.Build.Execution.TargetResult] failed to execute.This may be due to an invalid path, such as $(SolutionDir) being used in the csproj; try using relative paths instead.This may also be related to a missing default configuration directive. Refer to the Uno.SourceGenerator Readme.md file for more details. [D:\a\1\s\MvvmCross.Uno.Plugins\MvvmCross.Uno.Plugins.csproj]


"D:\a\1\s\MvvmCross.sln" (Build target) (1) ->
"D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.Droid\Playground.Uno.Droid.csproj" (default target) (52) ->
(_BuildApkEmbed target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2555,3): error XA5104: Could not locate the Android NDK. Please make sure the Android NDK is installed in the Android SDK Manager, or if using a custom NDK path, please ensure the $(AndroidNdkDirectory) MSBuild property is set to the custom path. [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.Droid\Playground.Uno.Droid.csproj]


"D:\a\1\s\MvvmCross.sln" (Build target) (1) ->
"D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.iOS\Playground.Uno.iOS.csproj" (default target) (53) ->
(CoreCompile target) -> 
  obj\iPhone\Release\g\NativeCtorsGenerator\Playground_Uwp_Views_SplitRootView_7a390d189302c0bb2259576b5372a334.g.cs(38,41): error CS1729: 'MvxWindowsPage' does not contain a constructor that takes 1 arguments [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.iOS\Playground.Uno.iOS.csproj]
  obj\iPhone\Release\g\NativeCtorsGenerator\Playground_Uwp_Views_SplitMasterView_fce8a9db9ad58b3a1c2ac65edee25ed0.g.cs(38,43): error CS1729: 'MvxWindowsPage' does not contain a constructor that takes 1 arguments [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.iOS\Playground.Uno.iOS.csproj]
  obj\iPhone\Release\g\NativeCtorsGenerator\Playground_Uwp_Views_BaseSplitDetailViewPage_2ef2704f899db0ff8ed912b0bb8dfd5a.g.cs(38,51): error CS1729: 'MvxWindowsPage<SplitDetailViewModel>' does not contain a constructor that takes 1 arguments [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.iOS\Playground.Uno.iOS.csproj]
  obj\iPhone\Release\g\NativeCtorsGenerator\Playground_Uwp_Views_BaseRootViewPage_5ee1c105965ede991ea888992056230e.g.cs(38,44): error CS1729: 'MvxWindowsPage<RootViewModel>' does not contain a constructor that takes 1 arguments [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.iOS\Playground.Uno.iOS.csproj]
  obj\iPhone\Release\g\NativeCtorsGenerator\Playground_Uwp_Views_DialogViewBase_95b54fb7e0bbebafaf478954e90a7118.g.cs(38,42): error CS1729: 'MvxWindowsContentDialog<ModalViewModel>' does not contain a constructor that takes 1 arguments [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.iOS\Playground.Uno.iOS.csproj]
  obj\iPhone\Release\g\NativeCtorsGenerator\Playground_Uwp_Views_ChildBase_982b5209a7bcad378c4f07a8d72d9a93.g.cs(38,37): error CS1729: 'MvxWindowsPage<ChildViewModel>' does not contain a constructor that takes 1 arguments [D:\a\1\s\Projects\Playground\Playground.Uno\Playground.Uno.iOS\Playground.Uno.iOS.csproj]

    16631 Warning(s)
    30 Error(s)
```

Playgrounds not building nor the Uno plugins project. Not sure exactly why.

**Comment by nickrandolph** [comment]
Closing this PR and raising a new one that's got a clean commit history

**Pull request closed without merging**
