### PR TITLE
Fix MvxModalPresentationAttribute support for IMvxTabBarViewController

### PR DESCRIPTION
**Pull request by Cybrosys**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix

### :arrow_heading_down: What is the current behavior?
Exception is thrown saying "Trying to show a tab without a TabBarViewController, this is not possible!" when using the MvxModalPresentationAttribute on a IMvxTabBarViewController.

### :new: What is the new behavior (if this is a feature change)?
It works.

### :boom: Does this PR introduce a breaking change?
No.

### :bug: Recommendations for testing
Have a IMvxTabBarViewController as a second view, with tabs, and add the MvxModalPresentationAttribute.

### :memo: Links to relevant issues/docs
#2331 

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Nuspec files were updated (when applicable)
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by Cybrosys** [comment]
I don't know how to merge multiple PR/commits into one, so sorry about that. The same regarding doing a "Rebase".

**Comment by nmilcoff** [comment]
Could you add a test case to Playground.iOS? We need to make sure the TabBarController is released / set to null when the modal is released.

**Comment by Cybrosys** [comment]
I also noticed an issue with MvxChildPresentationAttribute, basically it got ignored because there's a modal active, and the modal type never gets checked if it's a tabbarcontroller or not. Basically in-tab-navigation breaks.

**Comment by nmilcoff** [comment]
@Cybrosys any news? 🙂

**Comment by Cybrosys** [comment]
Yeah, I've got a updated presenter that supports it in my current project at work. The project isn't targeting the latest version so I'll need to check what's changed. I'm hoping to get some time during this week to catch up on the PR 😄

**Comment by Cybrosys** [comment]
I haven't created a test or updated the playground app yet. I'm using it myself, showing and closing the TabBarViewController modally with in-tab-navigation. I even did some tests where I specified that the TabBarViewController should be wrapped inside a NavigationController, but I don't recommend it haha. That's why there are extra checks inside `CloseModalViewController(UIViewController modalController)` when iterating over the UINavigationController's ViewControllers.

**Comment by nmilcoff** [comment]
I'll add a repro case to Playground, but I'm almost sure this solution won't work if you have a TabBarController as a root / child and then open a new one as a modal, because the previous one will be overwritten 🙁.

**Comment by nmilcoff** [comment]
@Cybrosys I've rebased the branch on top of current develop, and I have added a repro case to Playground.iOS.

As expected, the current solution leaks when there are two TabBarViewControllers (a root / child tab controller and a modal one)

**Comment by martijn00** [comment]
Please open a new PR with the requested feedback if this is still relevant to you.

**Pull request closed without merging**
