### PR TITLE
Added BindingEx WPA81 Project to Windows

### PR DESCRIPTION
**Pull request by ryanherman**
These are all the changes I had to make to get my WPA81 (Windows Phone 8.1 Store App) to allow BindingEx to be added to the project.

### CODE REVIEW

**Comment by slodge** [comment]
Thank for this

I can't merge it instantly because of a few Android changes, and because I'm not sure we want to collapse all the binding functionality down to CrossCore for the WPA81 level...

I know using more assemblies will mean more projects and dlls to track, but it's worth it so that the code on all platforms matches and so that bits of mvx can be reused independently.

This is a great and big first step though :) Thanks!

**Comment by ryanherman** [comment]
No problem!  Its working perfectly on our wpa81 project.  Thank you for giving me the first step o!

**Comment by martijn00** [comment]
@ryanherman there seems to be a lot of good stuff in here. Could you open some new PR's targeting the 4.0 branch, and separate concerns so it will be easier to merge? Maybe open one PR per type like: UWP(universal), WP8, etc.

**Comment by martijn00** [comment]
Closing this for now. Please open a new pull request targeting the 4.0 branch using the new namespaces if this still needs to be merged.

**Pull request closed without merging**
