### PR TITLE
Demonstrate Issue 2812

### PR DESCRIPTION
**Pull request by borbmizzet**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Demonstrates #2812 in playground
### :thinking: Checklist before submitting

- [x] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by martijn00** [comment]
You are using `RootViewModel` for both the Activity as the Forms Page. That is not valid.

**Comment by borbmizzet** [comment]
I thought that the Activity was supposed to be templated with the starting ViewModel.  I did find it odd why the documentation said to put it there as well as RegisterAppStart<TViewModel>().

**Comment by nickrandolph** [comment]
@martijn00 I think there's currently a bug where you have to specify a VM for the MainActivity, even though for a Forms app it's not used.

**Comment by nickrandolph** [comment]
@borbmizzet would you be able to rebase your branch to the develop branch.
Also, do you see the same issue if you remove the <RootViewModel> - this is no longer required.

**Comment by borbmizzet** [comment]
@nickrandolph  As of the latest develop, it works when I remove `<RootViewModel>` from `MainActivity<RootViewModel>`.   No more "No ViewModel for MainActivity" console log either.  I think this can be safely closed.

**Comment by nickrandolph** [comment]
@borbmizzet thanks for following up. I'll close this PR

**Pull request closed without merging**
