### PR TITLE
New MvxIosViewPresenter for iOS

### LINKED ISSUE #1274: MvxModalNavSupportIosViewPresenter does not use CurrentTopViewController
### Steps to reproduce
1. Use MvxModalNavSupportIosViewPresenter
2. Show a MvxViewController that inherits from IMvxModalIosView
3. Show a MvxViewController without IMvxModalIosView
### Expected behavior

The final show should use the NavigationController that contains the IMvxModalIosView to Push/Show the normal MvxViewController (CurrentTopViewController), not the MasterNavigationController. A push modal should allow for a new horizontal navigation. Preferable a way to close the modal as well, collapsing the whole navigation chain.

[Presenters in MvvmCross: Nested Modal Navigation in iOS](http://gregshackles.com/presenters-in-mvvmcross-nested-modal-navigation-in-ios/)
### Actual behavior

No navigation happens after showing a IMvxModalIosView and trying to Push/Show a normal MvxViewController.
### Configuration

**Version:** 4.1.0

**Platform:** iOS

### PR DESCRIPTION
**Pull request by nmilcoff**
This PR aims to resolve #1274. It takes the work done by @PelleRavn. This is also part of #1415. 

I have created a brand new view presenter, which means this won't be a breaking change (unless we set it as the default presenter).

Main features of this presenter are:
* Support for stack navigation 
* Support for nested stack navigation (modals)
* Support for modals _not_ wrapped in Navigation Controllers (`IMvxNavModalIosView` and `IMvxModalIosView`)
* Ability to display a "child" ViewModel in the current stack without restrictions
* Ability tu customize the way a modal view is displayed (animation, presentation style and transition style trough `MvxModalDisplayStyleAttribute` (class attribute)
* Support for modal ViewControllers that are presented manually by the user outside the navigation system of MvvmCross

This PR also includes
* Creation of `MvxNavigationController`, from suggestions of the referenced issue
* Creation of a Playground test project for the presenter: Following #1576 we should consider having a single playground for testing the "core" functionalities of the framework. CustomBinding sample and this one could be merged into one. Or we can bring APIExamples here, as @Cheesebaron sugested

-----

Current Status based on discussion and refactoring proposal:
- [x] Add MvxNavigationController
- [x] Add MvxSplitViewController
- [x] Add custom attributes for different presentation modes
- [x] Add support for navigation stack
- [x] Add support for Tabs navigation
- [x] Add support for _modal_ navigation stack
- [x] Add support for modals without navigation stack
- [x] Add support for SplitView as root
- [x] Remove interface `IMvxModalIosView`
- [x] Remove TabsPresenter from iOS-Support
- [x] Remove old presenters (`MvxModalNavSupportIosViewPresenter` and `MvxModalSupportIosViewPresenter`)
- [x] Remove parameter `wrapInNavigationController` from `ShowTabView` in `IMvxTabBarViewController`: Now that configuration is handled in the presenter
- [x] Add MvxSplitViewContainer
- [x] Complete refactor of `MvxIosViewPresenter`
- [x] Merge Tabs sample with Playground
- [x] Add close functionality (pretty hard to implement due to quantity of situations this presenter can handle)
- [x] ~~Add support for SplitView as child of a stack~~ : _Excluded by now, will do in a separate PR to reduce complexity._
- [x] ~~Support modal ViewControllers that are presented manually by the user outside the navigation system of MvvmCross~~: _Excluded, users are encouraged to display all views inside the MvvmCross navigation mechanism. If an app needs a different behavior, then it should use another / override this one._

### CODE REVIEW

**Comment by martijn00** [comment]
Fantastic initiative! I few things that i would like to add as goals for this refactoring:

* I would like to introduce a global system with View attributes for the iOS presenters. Currently the iOS tab presenter and sidemenu presenter already use them. This could be unified and for example for the sidemenu presenter, we would ideally only override a method where we control the attribute usage. We could also add the modal presentation to the attribute.
* To do this we can pull in the attributes to the main libs, and just override the new presenter in the iOS support package.
* The tabs are a standard part of iOS. I think we should support this in the default presenter.
* Can we support Segmented control navigation?

In my opinion this should be used as the new default presenter, and all others should be deprecated when the new one supports those use cases. If we do this for 5.0 it would be fine by me to break some behavior.

What do you think of those things?

**Comment by nmilcoff** [comment]
I really like the idea of attribute-based presenters. It keeps the code clean and extensible.

Here is a proposal for refactoring:
* Add support for Tabs to this presenter (we can potentially add support for SplitView too, but the more we add the more it will take to finish it)
* Create an iOS global attribute for presentation with common configuration members (presentation mode: tab, child, root, modal, ...) 
* Create separate attributes that inherit from a base one, to handle specific configurations for each presentation mode (for tabs: tabTitle, tabIconName, ... / for modals: PresentationStyle, TransitionStyle, ...)
* Both attributes will be grabbed in overridable methods from a base presenter 
* Set this presenter as the default presenter. This should be well documented when releasing 5.0

Segmented control navigation won't be so easy to include, since it doesn't work by itself as a navigation control (it can work together with a PageViewController for instance, but the SDK doesn't provide any automatic way to configure it). We can add a control and a featured presenter to support this on the iOS-Support package, but I would consider this out of the scope of this PR.

Async support (and showing-for-result) are super interesting to add too, but I guess both are related to #1634 and should be added during the creation of the new navigation system

**Comment by nmilcoff** [comment]
I have started the work on the refactoring. I've updated the PR description with the current status.

The original idea of having two separate attributes to handle common / specific configuration for each presentation mode has changed into a single attribute for each presentation mode (MvxTabPresentationAttribute, MvxRootPresentationAttribute, ...) that has all its configuration inside it.

Reason for this is that otherwise the "common configuration" attribute would have an enum that defines a PresentationMode... And enums cannot be extended. As a result, the presenter wouldn't be flexible at all.

**Comment by PelleRavn** [comment]
I've only looked at it very briefly, but it looks very promising. I'll have a deeper look at it, and try it out soon.

One thing that everyone (including myself) quietly ignores is the "clear stack" implementation. It's a complicated thing to do (my current implementation is a little hack-ish), but should we maybe find a way to do this as well?

**Comment by nmilcoff** [comment]
The PR is now ready to be reviewed.

It can be seen in action running the Playground project (you can customize the attributes over the View classes). It supports stack, tabs, split and modal navigation patterns. It is extensible, flexible and I hope you find it readable :)

**Comment by nmilcoff** [comment]
I just realized this change makes others iOS TestsProjects crash in runtime because of missing presentation attributes. Will commit this

**Comment by PelleRavn** [comment]
Wouldn't it be better if a view with no Attribute would be treated as MvxChildPresentationAttribute, so it's only views who behaves differently that needs a specific Attribute, instead of every single view needs one? Then it's a little more logical to people, than it just crashing asking them to please remember an attribute?

**Comment by martijn00** [comment]
I think if a view has no attribute the behavior should be the same as it is right now. If that means it's the `MvxChildPresentationAttribute` we should use that as default.

**Comment by nmilcoff** [comment]
Good suggestion! It is done now. In Playground project, `SecondChildView` has no attribute.

**Comment by martijn00** [comment]
Would it be an idea to use more default values for the attribute's? Like saying:
```
public bool WrapInNavigationController { get; set; } = true;
public UIModalPresentationStyle ModalPresentationStyle { get; set; } = UIModalPresentationStyle.FullScreen;
```

If we make some assumptions what is used most, it is easier to implement, while you can still set your own way if you want.

**Comment by nmilcoff** [comment]
I definitely agree with that. I'll add more default values to the attributes.

>Maybe you can improve the sample by adding a way to go back to the first screen, so you can choose a new navigation pattern to test.
Currently it is possible to initiate stack navigation again when Tabs are root, I'll add a way to do it when in Split is root too.

**Important note**, just in case you didn't notice: Once the root is changed the old root is dismissed (otherwise ViewControllers and all resources won't be disposed). There is no way to _go back_ to a previous **root**, only to navigate forward to a new instance of it.

I was also thinking about getting rid of the word `Presentation` in the attributes, since the context already gives an idea what the attribute will do. What do you guys think about this?

New names would be:
`MvxRootAttribute`
`MvxChildAttribute`
`MvxTabAttribute`
`MvxModalAttribute`
`MvxMasterSplitAttribute`
`MvxDetailSplitAttribute`

Only `MvxBasePresentationAttribute` remains the same.

**Comment by martijn00** [comment]
I didn't notice the root is changed, but you are right, that is a good thing. Maybe then just add a button to navigate to the first view again.

I'm not sure if removing `Presentation` from the name makes it more clear.

**Comment by PelleRavn** [comment]
I definitely don't think you should remove 'Presentation' in the names. I think it should be explicit and it also makes it easier to find them with the intellisense.

**Comment by nmilcoff** [comment]
Thanks guys, it makes sense.

I've added some more default values and improved the sample renaming some buttons and adding a way to initiate stack navigation when SplitView is the root.

**Pull request merged**
