### PR TITLE
Fixed unified value types conversion when binding to a nfloat, nint or uint from a managed equivalent value type.

### PR DESCRIPTION
**Pull request by ggirard-distech**
Fix for #878 

Test project used for this fix available at https://github.com/ggirard-distech/MvvmCross_Issue878_TestProject.git

### CODE REVIEW

**Comment by ggirard-distech** [comment]
Looks like I did not properly associate my PR to the original issue (PR does not appear in #878 history...).
Does anybody can help me with this?

**Comment by Dexyon** [comment]
I do see the reference in the original issue as a reference, just after the comment of Martijn

**Comment by Dexyon** [comment]
I see you have a slightly altered version of your code layout settings. Try to keep the project in the same codings style.

**Comment by ggirard-distech** [comment]
@Dexyon Yeah I saw that for the code layout. But it was already inconsistent before I edited the file.

I haven't heard about any code style for MvvmCross (whether based on VisualStudio style of Xamarin Studio), so I took the decision to use Visual Studio style. Is this a problem?

**Comment by martijn00** [comment]
@ggirard-distech The problem with a different style is that it is harder to see what really changed. I am wondering what @lothrop thinks of this?

**Comment by lothrop** [comment]
I like both style and content. :smile:

**Comment by Cheesebaron** [comment]
Looks good, is there any chance you could make a small sample where you use this?

**Comment by ggirard-distech** [comment]
@Cheesebaron already did here https://github.com/ggirard-distech/MvvmCross_Issue878_TestProject.git
I hope it's not too complicated for such a little change... I was looking to recreate a kind of custom control from a third party I am using in my project

**Comment by martijn00** [comment]
Thanks!

**Pull request merged**
