### PR TITLE
Revert MvxRecyclerView Header/Footer and Grouping Features

### LINKED ISSUE #1730: Custom MvxRecyclerViewAdapters don't work anymore
If you create a dummy `MvxRecyclerAdapter` it's `ItemSource` property gets set to an instance of
`MvvmCross.Droid.Support.V7.RecyclerView.ItemSources.MvxRecyclerViewItemsSourceBridgeHeaderFooterDecorator`

and not something reasonable like a list of stuff.

### PR DESCRIPTION
**Pull request by kjeremy**
This reverts the RecyclerView header/footer grouping support added for 5.0.

There are some issues with breaking existing custom adapters so we are reverting these features for the 5.0 release.

Fixes #1730, #1743
Sort of obsoletes #1642

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Looks good to me.

Will give this a spin soon.

Next time, as discussed briefly on Slack, we shouldn't merge features like these if they haven't actually been tested and demonstrated properly. Sure the code looked good and promising, that is however not enough to ensure that we don't make a big regression. Since the author (@thefex) hasn't responded in #1730 and we are soon to release something stable, I agree with @kjeremy that this shouldn't make it into 5.0, not as-is.

**Comment by MarcBruins** [comment]
Lets also not merge new features without having any docs about how they work. It should be really easy for devs to add documentation about there changes with the new website.

**Comment by kjeremy** [comment]
Can we get this in before the next nuget beta?

**Comment by martijn00** [comment]
Is it an idea to pull over the new features to a new adapter instead of completely removing them?

**Comment by kjeremy** [comment]
Not right now.  I think this will need to be redone.

**Pull request merged**
