### PR TITLE
Added netcoreapp3.1 support

### LINKED ISSUE #3664: Add .NET Core 3.1 support & publish supporting (Beta-) Nuget-Packages
## 🚀 Feature Requests

.NET Core 3.0 support for WPF has been added to the MvvmCross develop branch a few weeks ago. Currently there are no supporting Nuget packages as there has been no new MvvmCross version.

.NET Core 3.1 is out as a Long Time Support (LTS) release. As we're planning to migrate to .NET Core 3.1 over the holidays it would be more than helpful to have supporting MvvmCross (beta) Nuget packages.

Of course I'm aware of the coming holiday season & I'm feeling in no way entitled to receive any quick help from you on this issue. I've done a contribution to the project in the past & am more than willing to do whatever I can to support getting this issue resolved.
As a small sign of our appreciation we would also donate US-$100 to the project.

### Describe the feature
From my (maybe limited) understanding adding .NET Core 3.1 support should mainly consist in adding `netcoreapp3.1` to  `<TargetFrameworks>net461;netcoreapp3.0</TargetFrameworks>` in https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Wpf/MvvmCross.Platforms.Wpf.csproj.
Also the release of a new (beta) version including the publication of Nuget packages would be helpful.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

### PR DESCRIPTION
**Pull request by HaraldMuehlhoffCC**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?
.NET Core 3.1 (LTS) is not supported

### :new: What is the new behavior (if this is a feature change)?
Added netcoreapp3.1 target to MvvmCross

### :boom: Does this PR introduce a breaking change?
No

### :memo: Links to relevant issues/docs
Fixes #3664

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Looks good to me! Thank you for the PR!

**Comment by Cheesebaron** [comment]
6.5.0-alpha.88 has this code 👍

**Comment by JensSchadron** [comment]
Hi @Cheesebaron
I just tried 6.5.0-alpha.88 in a fresh WPF application running on .NET Core 3.1, however... it seems like the package is still missing all the necessary classes (eg: MvxWpfSetup, ...)
I don't know much about the build process, but my guess is that something is wrong with the build condition in the MvvmCross.Platforms.WPF.csproj file.

**Comment by Cheesebaron** [comment]
@JensSchadron glad you got it to work 👍

**Pull request merged**
