### PR TITLE
Allow multiple EnsureInitialized calls

### PR DESCRIPTION
**Pull request by andyci**

### CODE REVIEW

**Comment by martijn00** [comment]
What is there left to be done for this?

**Comment by andyci** [comment]
Not sure, I have been using it in my application successfully so perhaps it just needs to be reviewed as it is a pretty integral part of the framework

**Comment by martijn00** [comment]
I just came across https://github.com/MvvmCross/MvvmCross/issues/955 There is some interesting code in there. Can we make sure we can combine your and that code, to fix both cases?

**Comment by andyci** [comment]
That code is slightly different.  This pull request makes a similar change but keeps the EnsureInitialised method synchronous so we don't have to update all the places we use EnsureInitialised and turn them async.

**Comment by davidschwegler** [comment]
@martijn00 @andyci 

This PR is a good start, but has a critical bug in it. 

Multiple calls to EnsureInitialize probably work fine. Calling EnsureInitialize and then InitializeFromSplashScreen also probably works. However, calling InitializeFromSplashScreen and *then* EnsureInitialize crashes.

1) App calls InitializeFromSplashScreen (eg app starts up normally)
   - [_initializationStarted is set to true](https://github.com/MvvmCross/MvvmCross/pull/1253/files?diff=split#diff-7df39d8e4f2f85a961e1d3887d24e817R88) and [async init starts](https://github.com/MvvmCross/MvvmCross/pull/1253/files?diff=split#diff-7df39d8e4f2f85a961e1d3887d24e817R94)
2) While initializing async, EnsureInitialized is called on the main thread (lets say some push notification arrives to the device and it needs to process it)
   - [_initializationStarted is NOT checked](https://github.com/MvvmCross/MvvmCross/pull/1253/files?diff=split#diff-7df39d8e4f2f85a961e1d3887d24e817R49) (this is the bug), and this._setup.Initialize() is called anyways
  - [MvxException is thrown](https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Core/Core/Platform/MvxSetup.cs#L44) because setup has already started. 

Workaround? None. I can't just catch and ignore this exception, because any later calls will be permanently stuck waiting on IsInitialisedTaskCompletionSource because [SetResult](https://github.com/MvvmCross/MvvmCross/pull/1253/files?diff=split#diff-7df39d8e4f2f85a961e1d3887d24e817R58) will never be called on it.

**Comment by davidschwegler** [comment]
Please do create a separate issue if that's better -- just wanted to initiate the discussion here since that's where the change was made. 

We currently can't upgrade to 4.2 with this code in it, though. (I'm the author of the workaround to the previous issue described in #955, btw).

**Pull request merged**
