### PR TITLE
[WIP] Add support for async startup

### PR DESCRIPTION
**Pull request by nickrandolph**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?
Currently the built in MvxAppStart only supports a synchronous startup. In cases where a splash screen is used, it should be possible to use an async startup which would allow the Initialize method to do long running actions. Currently this is achieved by overriding the default MvxAppStart.

### :new: What is the new behavior (if this is a feature change)?
Added support for StartAsync into IMvxAppStart
Altered SplashScreen (Android only) to make use of StartAsync
TODO: Add equivalent splash screen view to other platforms to show how this could work

### :boom: Does this PR introduce a breaking change?
Yes - some interfaces now return Task where previously was void

### :thinking: Checklist before submitting
Follow up PR to: https://github.com/MvvmCross/MvvmCross/pull/2784
In response to Issue: https://github.com/MvvmCross/MvvmCross/issues/2829

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Rebased onto current develop
Note: This needs to be rebased onto v6.1 after PR 2784 has been merged

### CODE REVIEW

**Comment by nmilcoff** [comment]
This will be a really nice improvement. However I don't think we should include this PR on a minor version, as there will be a lot of breaking changes.

**Comment by nickrandolph** [comment]
@nmilcoff what breaking changes do you see that will affect a large number of users? I'm really keen to get this into v6.1 as it addresses an area that v6 broke for a lot of people

**Comment by nickrandolph** [comment]
@martijn00 what else do we need to do in order to get this PR completed?

**Comment by nmilcoff** [comment]
@nickrandolph all apps using custom ViewPresenters will break, and the interface changes for `IMvxApplication` will also have an impact. Other than that can we please move all the IoC changes to a separate PR? There is no description about them, which will make them hard to track in the future (also probably a bit unrelated?)

**Pull request closed without merging**
