### PR TITLE
MvvmCross 6.4.0 blog post

### PR DESCRIPTION
**Pull request by Cheesebaron**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
docs

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [x] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Wtf? This is not what I committed...

**Comment by FinHorsley** [comment]
With the changes to using `System.Drawing.Color` in [PR#3456](https://github.com/MvvmCross/MvvmCross/pull/3456), do we have to use the plugin to convert to native colours (e.g. `UIColour`)?

We currently have the following converter, but I don't see how this will work given that `System.Drawing.Color` isn't available from the iOS project (might have missed something here though)
```
public static UIColor ToNativeColour(this MvxColor mvxColor)
{
     return UIColor.FromRGBA(mvxColor.R, mvxColor.G, mvxColor.B, mvxColor.A);
}
```

**Comment by Cheesebaron** [comment]
@FinHorsley yes, that logic is still in the plugin. I think we should move it into the core project in the future.

**Comment by FinHorsley** [comment]
Ok 🙂 Does this mean we have to use the plugin to convert to native?

Ideally I'd rather not have to use the plugin, and just have a custom extension method on `System.Drawing.Color` (if this is possible?)

**Comment by Cheesebaron** [comment]
@FinHorsley depends on where you want to use it. But sure, you have the rudder and here is a captain hat captain hat

Joke aside. The converters are mainly for binding from ViewModel to View. We have a couple of different Binding Targets provided that will use `ToNative()` from the Color plugin.

**Comment by Strifex** [comment]
@FinHorsley hey if you're having issues referencing System.Drawing.Color in iOS......see the notes in the PR I made, essentially System.Drawing is referenced from a very odd version of OpenTK in Xamarin.iOS and Xamarin.Mac so include that reference in the project file in order for System.Drawing to be able to be seen.

**Pull request merged**
