### PR TITLE
Bump Minimum Supported Version of Android to API 23 (M).

### PR DESCRIPTION
**Pull request by Strifex**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

This PR bumps the android playground projects minimum supported version to 23 and removes any runtime checks in the android platform that are no longer necessary.  Effectively this makes Android API 23 (Marshmallow) the minimum supported version of Android for MvvmCross.  The idea here is that this is a good first step to removing unnecessary complications in some of the core android files (such as MvxLayoutInflator) and also reduces maintenance overhead going forward as we no longer support legacy versions of android.

I chose version 23 for many reasons.  The core reason is because as of April 2020, versions 22 and below made up ~15% of the device distribution according to google You can validate and see the current number on Android Studio's dashboard since google removed it from their website for some reason.  That number is only steadily decreasing as time goes on, so we can be sure that the framework is still supporting the vast majority of users.

### :arrow_heading_down: What is the current behavior?

The framework can reliably be used to build apps that run on devices running versions of android older than API 23 (Marshmallow, also known as version 6.0).

### :new: What is the new behavior (if this is a feature change)?

The framework cannot reliably be used to build apps that run on devices running versions of android older than API 23 (Marshmallow, also known as version 6.0).  However, complications from the android code can / are removed and maintenance will be easier going forward.

### :boom: Does this PR introduce a breaking change?

Yes, you can no longer utilize MVX to build android apps that target a minimum API level of < 23.

### :bug: Recommendations for testing

Test any app on API level 23 or higher and ensure it runs as it did previously - I tested with the playground project and it was fine.

### :memo: Links to relevant issues/docs

- Article on Android Distribution as of April 2020, but you can check Android Stuidio for the latest numbers (https://9to5google.com/2020/04/10/google-kills-android-distribution-numbers-web/)

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [X] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [X] Rebased onto current develop

### CODE REVIEW

**Comment by Strifex** [comment]
Looks like there might be an issue with sonar or something else in the pipeline @Cheesebaron

**Comment by Cheesebaron** [comment]
Yeah, sonar is breaking on building forks. Don't worry about that.

**Comment by Strifex** [comment]
@Cheesebaron I updated this PR with your latest changes to AndroidViewPresenter so it should be good to review - just sonar failing likely due to previous issue you mentioned.

**Review by Cheesebaron — APPROVED** [review]

**Comment by Cheesebaron** [comment]
Thanks for this one!

**Comment by radioactiveman** [comment]
Did the support for older Android versions caused that much maintenance overhead?
From the lines of code it looks feasible.

It's just my humble opinion but I would not yet require Android 6.0 or later.
Xamarin.Forms and Xamarin.Essentials also still support older versions.

https://docs.microsoft.com/en-us/xamarin/essentials/platform-feature-support?context=xamarin/android

**Comment by Strifex** [comment]
@radioactiveman There is virtually no marketshare for devices less than Android 5.0 and even the 5.0/5,1 userbase is shrinking rapidly.  There was significant changes in Android 5.X and 6.0 that changed the way certain operations are done.  In general we needed to move up to at least API 21+ (Android 5.0) in order to remove some of the excess layout inflator / transition checks in the framework.  This also allows us to get a better look at the layout inflator and how we can improve it since we've removed most (not all) of the legacy inflator code that was only needed to run on extremely old devices.

Also - Android 6.0 at a minimum still targets close to 90% of devices according to google statistics and that number will only grow over the next year.  Even MAUI (which replaces xamarin.forms) is bumping up the minimum supported version when it comes out next year.

That being said this PR was really just a nice way to make sure we weren't using obsolete/legacy code and serve as a "step 1" to improving some of the legacy android code.  It wasn't meant to make any significant movements forward yet  - just give API options for the future and remove the need to maintain the obsolete methods/overloads that have existed for so many years.

**Comment by Cheesebaron** [comment]
It is just a big can of worms every time someone touches code that has to be backwards compatible with ancient Android versions.

If you are working on Apps supporting anything older than Android 6, I am sorry for you.

Also, please voice your concerns _before_ a PR gets merged, you've only had since August 17th 😄

**Pull request merged**
