### PR TITLE
Xamarin Forms 5.0 Support

### PR DESCRIPTION
**Pull request by epsmae**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Preparation for Xamarin.Forms 5.0 Support. Due to renaming in Xamarin.Forms 5.0 it is not anymore compatible with Xamarin.Forms 4.6 which is currently used in MvvmCross.

### :arrow_heading_down: What is the current behavior?
Xamarin.Forms.MasterDetailsPage is used.

### :new: What is the new behavior (if this is a feature change)?
Xamarin.Forms.FlyoutPage is used.

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
All controls should be checked

### :memo: Links to relevant issues/docs
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0-api

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [x] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/MvvmCross/MvvmCross?pullRequest=3972) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/MvvmCross/MvvmCross?pullRequest=3972) before we can accept your contribution.<br/><br/>:x: epsmae [sign now](https://cla.dotnetfoundation.org/MvvmCross/MvvmCross?pullRequest=3972)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/MvvmCross/MvvmCross?pullRequest=3972) it.</sub>

**Comment by filipoff2** [comment]
I hope this change is paid one.

**Review by fedec93 — APPROVED** [review]

**Comment by epsmae** [comment]
Changed to use this weeks stable Xamarin Forms 5.0 release.
I had to adjust the configuration of Xamarin.Forms.iOS locally in order to use Windows iOS build without a mac.
Debugging and hot reload works really smooth.
Let me know if I am allowed to add these changes to the repo:

image
image

The merge conflicts are still pending as am unable to build with visual studio when I merge from develop due to the new .target files:
https://github.com/MvvmCross/MvvmCross/issues/4043

**Comment by Cheesebaron** [comment]
For #4043 can you try add a `Directory.Build.props` file to the projects folder with all the playground projects with just:

```xml
<Project>
</Project>
```

This should override the central packages stuff for these.

**Comment by epsmae** [comment]
@Cheesebaron Android and iOS seems to be fine but it WPF and UWP doesn't look that well.
I have never used Xamarin.Forms with WPF or UWP may you can guide me if this is an issue on mvvmcross side.

**Comment by Cheesebaron** [comment]
@epsmae I will have a look. Looks like build is green. Do you mean the Playground for WPF and UWP doesn't run?

**Comment by epsmae** [comment]
@Cheesebaron yes sorry, I mean the playground.
They do run but I expected the menu to look different.

**Comment by Cheesebaron** [comment]
@epsmae I don't think they have the same content as the Android/iOS apps. So if they run, that is OK!

**Comment by Cheesebaron** [comment]
Works great here. Thank you for this update!

**Review by Cheesebaron — APPROVED** [review]

**Comment by mrtnkrstn** [comment]
Hi

When will this be available?

**Comment by Cheesebaron** [comment]
When 8.0.0 is released, hopefully sometime soon.

**Comment by mrtnkrstn** [comment]
Sure, thanks, I'll be happy to test it out.

**Comment by mrtnkrstn** [comment]
Hi, any updates on this?

**Comment by Cheesebaron** [comment]
@mrtnkrstn sorry, been busy. Will look at publishing some packages ASAP 👍

**Comment by Cheesebaron** [comment]
@mrtnkrstn the packages are on our MyGet feed: https://www.myget.org/F/mvvmcross/api/v3/index.json 8.0.0-alpha.145 is the latest

**Comment by mrtnkrstn** [comment]
Thank you @Cheesebaron, I will try them out and let you know.

**Comment by mrtnkrstn** [comment]
Hi @Cheesebaron sorry for the late feedback, I tried the alpha and didn't find any issues. Please let me know when you plan to release the stable version as we would like to upgrade our app to Xamarin.Forms 5, but this is holding is back. Thanks!

**Comment by mrtnkrstn** [comment]
Hi @Cheesebaron any updates? Thank you.

**Pull request merged**
