### PR TITLE
Update to .NET Standard

### PR DESCRIPTION
**Pull request by martijn00**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

This migrates all projects to SDK style projects and switches PCL's to .NET Standard

### :boom: Does this PR introduce a breaking change?

YES!

### :memo: Links to relevant issues/docs
https://github.com/MvvmCross/MvvmCross/pull/2385

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Nuspec files were updated (when applicable)
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Todo:

- [ ] Fix usage of PreserveAttribute, it conflicts many places with the one Xamarin provides
- [ ] Move away from MvxTrace, so many warnings in the build output

**Comment by nmilcoff** [comment]
Would it be an idea to remove the `Obsolete` attribute from MvxTrace for now?

**Comment by Cheesebaron** [comment]
There is some derpage going on with the Android Resource files. I've tried removing most of what we have in our csproj files, because most should be handled by MSBuildSDKExtras anyways.

However, when doing so it then complains about multiple Resources folders and the generated output. It should only have one in `MvvmCross`, but 4 are generated for `MvvmCross.Binding.Droid.Resource`, `MvvmCross.Resource`, `MvvmCross.Dialog.Droid.Resource` and `MvvmCross.Droid.FullFragging.Resource`. Each of these in turn generate `[assembly: global::Android.Runtime.ResourceDesignerAttribute(...]`, only one is allowed.

We need to combine the Resources for all the droid stuff that is in the MvvmCross project into one to fix this.

**Comment by Cheesebaron** [comment]
Builds on my machine now. Also fixed usage of PreserveAttribute, so we have less warnings.

Now to fix the 200 or so warnings for MvxTrace usage.

**Comment by kjeremy** [comment]
I know this is WIP but let's definitely squash this before merging.

**Comment by Cheesebaron** [comment]
@kjeremy Yep, will need squashing.

I've disabled NUnit test for now, since the Console Runner does not like netcoreapp2.0 projects. I tried with dotnet-cli it seems to run the tests, so need to update the build script to use that instead.

**Comment by Cheesebaron** [comment]
AppVeyor now has Artifacts attached, I've chucked the nupkg files in there if someone wants to try these builds out: https://ci.appveyor.com/project/MvvmCross/mvvmcross/build/artifacts

**Comment by Cheesebaron** [comment]
Let's merge this. We will continue working on this in separate PR's.

**Pull request merged**
