### PR TITLE
Migrate Test.Core to PCL

### LINKED ISSUE #523: MvxIoCSupportingTest for WindowsPhone and others?
Hi, is it possible to use MvxIoCSupportingTest for platforms beyond net45? It is found in Test.Core, suggesting it is a portable class, but it really is a net45 type.

### LINKED ISSUE #1375: MvvmCross.Tests nuget can't be added to a PCL project
`MvvmCross.Tests` nuget is only configured to be used in a `Console Application`, while a nUnit based test suit only needs to be a Portable Class Library (which is actually what the old documentation references [here](https://github.com/MvvmCross/MvvmCross/wiki/Testing#creating-a-test-assembly) ). 

Adding the .dll to a PCL works.

I'm unable to PR this currently but we might just need to change the [.nuspec]() to have:

```
<!-- PCL -->
<file src="..\bin\Release\Mvx\Console\MvvmCross.Test.Core.MvvmCross.Test.Core.dll" target="lib\portable-net45+win+wpa81+wp80" />
<file src="..\bin\Release\Mvx\Console\MvvmCross.Test.Core.MvvmCross.Test.Core.pdb" target="lib\portable-net45+win+wpa81+wp80" />
```
### Steps to reproduce
1. Create a `Class Library (Portable)`
2. Add `MvvmCross.Tests` nuget
### Expected behavior

Nuget would be added to a PCL project.
### Actual behavior

Error, output will say `MvvmCross.Tests doesn't support .NETPortable,Version=v4.5,Profile=Profile259`

**Version:** 4.2.0

**Platform:** PCL

### PR DESCRIPTION
**Pull request by willsb**
Closes #1375
Closes #523

Possible upgrades that can be added to this PR, if requested by the reviewer:

- Changing the OutputPath from `\bin\Debug\Mvx\Console\` to `\bin\Debug\Mvx\Portable\`
- Upgrading NUnit from 2.6.2 to latest

### CODE REVIEW

**Comment by martijn00** [comment]
Looks good to me. Can you add the upgrades as well?

**Comment by martijn00** [comment]
Now i look at the nuspec... Shouldn't it have a dependency on NUnit 3.6.0?

**Comment by willsb** [comment]
Oh yeah, you're correct. It should also depend on MvvmCross.Core

**Comment by martijn00** [comment]
Thanks!

**Pull request merged**
