### PR TITLE
Reverts IsXamarinForms changes in Playground

### PR DESCRIPTION
**Pull request by tbalcom**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix

### :arrow_heading_down: What is the current behavior?
<PackageReference/> to Xamarin.Forms is incorrectly being added to Playground.Droid.

### :new: What is the new behavior (if this is a feature change)?
<PackageReference/> to Xamarin.Forms is no longer being added to Playground.Droid.

### :boom: Does this PR introduce a breaking change?
No.

### :bug: Recommendations for testing
Rebuild and verify there is no longer a NuGet dependency to Xamarin.Forms in Playground.Droid.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
@tbalcom are you sure that XF was being included in the Playground.Droid project? Looking at the props it looks like it shouldn't be. This PR is a regression on the the changes @martijn00  and I both proposed around simplifying the reference to XF, so I don't think this is a great fix. Better for us to find out why Playground.Droid would be getting a reference to XF.

**Comment by tbalcom** [comment]
I brought it up on Slack this morning and he asked for a PR. You can see the Xamarin.Forms package shows up in Playground.Droid and can't be removed because of the .props file.

**Comment by nickrandolph** [comment]
Ok, I just saw the conversation - reverting this change isn't the way to go. Instead I think we should add a separate targets file that gets included in the appropriate projects (mvvmcross.forms and the playground sample projects). This way we can still easily adjust forms version in one place.

**Comment by nickrandolph** [comment]
FYI - MS is aware of this as an issue (see https://github.com/dotnet/project-system/issues/2129)

**Comment by nickrandolph** [comment]
@tbalcom I hope you don't mind but I pushed changes to your branch that keep the intent of the original commit (central place to adjust XF versioning) whilst overcoming the issue that you quite rightly identified. I've confirmed the issue with the MS product team (see issue linke above), so for the moment we'll have to make do with the slightly less tidy workaround. 
Thanks again for picking this up and raising a PR to get it fixed

**Pull request merged**
