### PR TITLE
[WIP] Make MvxContentView(or any other Mvx Forms View)<>.ViewModel property bindable

### PR DESCRIPTION
**Pull request by borbmizzet**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Make MvxContentView(or any other Mvx Forms View)<>.ViewModel a bindable property.
This is just an idea, and not a complete implementation yet, but I wanted to know what you guys thought. (Duplicate of PR #2870, which I accidentally broke by deleting my remote branch)

### :arrow_heading_down: What is the current behavior?
MvxContentView<>.ViewModel is not bindable, and accessing a property in it from xaml using `{Binding Source={x:reference mvxViewName}, Path="..."}` requires `Path="BindingContext.DataContext.PropertyName"` and PropertyName does not get suggested in intellisense, as BindingContext.DataContext is not strongly typed.  If you use `Path="ViewModel.PropertyName"`, and ViewModel gets modified for some reason (ie. setting it in the consumer), then the change doesn't get propagated to the view.

### :new: What is the new behavior (if this is a feature change)?
MvxContentView<>.ViewModel is bindable and still functions the same relative to MvxContentView.DataContext

### :boom: Does this PR introduce a breaking change?
 only if you're using `{Binding Source={x:reference mvxViewName}, Path="ViewModel.PropertyName"}` and you expect that setting ViewModel to a new object will not propagate to the view. 

### :memo: Links to relevant issues/docs

#2825 
### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
@borbmizzet would you mind rebasing this please?

**Comment by borbmizzet** [comment]
@nickrandolph Sorry about that, I could have sworn I had rebased it already.

**Comment by borbmizzet** [comment]
re-rebased onto current release/6.1.0

**Comment by borbmizzet** [comment]
@nickrandolph @martijn00 @Cheesebaron If one of you could take a look at this implementation, I can correct anything that is not up to par or implement it for the rest of the MvvmCross.Forms.Views.MvxFormsView<TMvxViewModel> in the same way if I get approval on this first one.

**Comment by martijn00** [comment]
I see a couple of things here, but to make it easier i think we need to split this up. Can you make a new PR that only adds the BindableProperty and not the Events? That would be easier to get merged, and than we can work on the other things in a separate PR.

**Comment by martijn00** [comment]
@borbmizzet I'm trying to reach out to you on Slack. Can you ping me?

**Comment by nickrandolph** [comment]
@martijn00 @borbmizzet I'm closing this issue as I think that https://github.com/MvvmCross/MvvmCross/pull/2934 should address the requirements here?

**Comment by borbmizzet** [comment]
@nickrandolph Yes, this was superceded by #2934.

**Pull request closed without merging**
