### PR TITLE
Added dummy packages to ease migration from HotTuna.

### PR DESCRIPTION
**Pull request by lothrop**

### CODE REVIEW

**Comment by martijn00** [comment]
Maybe we should put this in a separate folder "deprecated" under nuspecs

**Comment by lothrop** [comment]
Done. Should we create the nuspecs for the other projects, too?

**Comment by martijn00** [comment]
I think some others like android an forms only existed in beta. They might not require nuspecs?

**Comment by lothrop** [comment]
Right. That would leave the plugins.

**Pull request merged**
