### PR TITLE
#1894 Fixed problem where C# version of event handlers do not unsubsc…

### PR DESCRIPTION
**Pull request by Bowman74**
…ribe from native events as expected. Instead switch to native style events to get expected behavior.

## :sparkles: What kind of change does this PR introduce? 
Bug fix

## :arrow_heading_down: What is the current behavior?
Android Appeared event fires multiple times.  

## :new: What is the new behavior (if this is a feature change)?
Android Appeared event only fires once

## :boom: Does this PR introduce a breaking change?
No

## :bug: Recommendations for testing
Check lifecycle events for activities.

## :memo: Links to relevant issues/docs
#1894

## :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [x] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [x] Nuspec files were updated (when applicable)
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by kjeremy** [comment]
So... this worries me.  Is there a Xamarin bug this corresponds to?  If not then one needs to be filed.

**Comment by Bowman74** [comment]
@kjeremy 
I have submitted a bug to Xamairn here:

https://bugzilla.xamarin.com/show_bug.cgi?id=57031

It also includes a link to a simple (non-MvvmCross) project that demonstrates the difference in behavior of these two methods of using events that handle the GlobalLayoutListener.

**Comment by Bowman74** [comment]
@kjeremy I have updated the other Mvx components as you requested to use the native event style. Let me know if you need anything else done.

**Comment by Cheesebaron** [comment]
I really don't like that we keep a reference to the inflated view. However, I guess that is the best way to be able to easily unsubscribe later on.

**Comment by kjeremy** [comment]
Let's give it a few days and hear what xamarin has to say before merging.

**Comment by Bowman74** [comment]
@Cheesebaron To be fair we were keeping a class level reverence to the inflated view before, just the way the code was written made it less obvious. We used the view reference scoped in the method in the event handler. What the compiler does so that reference doesn't go out of scope is elevate that to a class level reference. It's the source of a lot of inadvertent memory leaks.

**Comment by kjeremy** [comment]
Out of curiosity does this fix the bug?

```csharp
EventHandler onGlobalLayout = null;
onGlobalLayout = (sender, args) =>
{
    var vto = (ViewTreeObserver)sender;
    if (vto.IsAlive)
    {
         vto.GlobalLayout -= onGlobalLayout;
         ViewModel?.Appeared();
    }
};
```

Stackoverflow suggests that you need to remove the listener from the `ViewTreeObserver` that is in use.

**Comment by Bowman74** [comment]
@kjeremy Sorry, the code you proposed doesn't work. The version of the ViewTreeObserver sent in the sender parameter of the event is never alive and it isn't the same instance the event was added to so the event couldn't be removed from it. 

I could add the IsAlive code before removing the event handler in the new code if you want. Having said that, based on the lifecycle, there should never be a case where IsAlive isn't true.

**Comment by thongdoan** [comment]
Should we change to below ?, We will add a "raised" flag, and on next version of Xamarin maybe they will fix it
```
public override void SetContentView(int layoutResId)
        {
            var view = this.BindingInflate(layoutResId, null);

            var weakThis = new WeakReference(this);
            var weakView = new WeakReference(view);
            var weakOnGlobalLayout = new WeakReference(null);

            bool raised = false;
            EventHandler onGlobalLayout = null;
            onGlobalLayout = (sender, args) => {
                if (raised)
                    return;
                raised = true;
                var strongThis = weakThis.Target as MvxAppCompatActivity;
                var strongView = weakView.Target as View;
                var strongOnGlobalLayout = weakOnGlobalLayout.Target as EventHandler;

                if (strongOnGlobalLayout != null && strongView != null) {
                     strongView.ViewTreeObserver.GlobalLayout -= strongOnGlobalLayout;
                }
                strongThis?.ViewModel?.Appeared();
            };

            weakOnGlobalLayout.Target = onGlobalLayout;
            view.ViewTreeObserver.GlobalLayout += onGlobalLayout;

            SetContentView(view);
        }
```

**Comment by Bowman74** [comment]
@kjeremy I made the changes you requested to check the IsAlive variable. I also clear out the _view pointer when the even is unhooked as it is no longer needed.

**Pull request merged**
