### PR TITLE
Mvx550 windows suspension

### PR DESCRIPTION
**Pull request by tal33**
Fix for issue 550 (Windows suspension) as proposed in https://github.com/MvvmCross/MvvmCross/issues/550

Additionally added automatic suspensionManager.RegisterFrame since it needs the same _rootFrame object as MvxStoreSetup owns (and also to make it easier to use) with backwards compatibility (optional constructor parameter with default null)

Notes:
- also made the same changes to WindowsStore-classes without testing
-- maybe WindowsPhone-classes need this path, too?
- added a Windows-Only-Solution to facilitate building MvvmCross without Xamarin

### CODE REVIEW

**Comment by slodge** [comment]
Thanks

I've been trying to work out how to test this...

I'm a bit tempted just to pull it in and then to let people scream if it breaks things... Im just holding off for now...

Wonder if @jonstoneman or any other Win-wizard has an opinion?

**Comment by tal33** [comment]
I think I've tested it quite a bit for Universal Apps but I have no experience with classic Windows Store (WinRT 8) apps but since the original patch was suggested for that target I'm quite confident it'll work (I'm wondering who is still targeting WinRT Store Apps and not switching to Universal Apps anyways ;-)

Right now, if you register a SuspensionManager for Universal Apps your app just crashes. Can't get much worse :-)

BTW: I've uploaded a small Universal App for testing it (I've used Debugger-->Lifecycle Events, especially Suspend & Shutdown and then restarting it)

https://github.com/tal33/Foo/

**Comment by slodge** [comment]
Thanks :+1: :+1: :+1: :+1:

Wondering what to do with the `Foo` sample - would be good to somehow publicise and reuse that sample :)

**Comment by tal33** [comment]
Since my Foo-git repro is my universal playing field, I've created a branch with the latest version of that sample for this issue as a reference on how suspend/resume support in universal apps can be implemented:
https://github.com/tal33/Foo/tree/Demo-App-for-Mvx-Issue-550

I've updated the Foo sample a little bit:
- it references MvvmCross 3.5.1-alpha1 from nuget instead of included assemblies
- cleaned up app.xaml.cs and setup.cs-code to make it more readable

If I can help with the sample, please let me know. What I would suggest is that I update "_Windows Store UI.txt" with my version of app.xaml.cs as well as Setup.cs.pp with my version of Setup.cs. Maybe with defaulting to no suspend/resume support and only adding the relevant changes as comments.

**Pull request merged**
