### PR TITLE
Added protected constructor to MvxFrameControl...

### LINKED ISSUE #890: MvxFrameControl does not expose the protected constructor with IntPtr...
MvxFrameControl should expose:

protected MvxFrameLayout(IntPtr javaReference, JniHandleOwnership transfer)
:base(javaReference, transfer)
{}

Shouldn't it?

### PR DESCRIPTION
**Pull request by azchohfi**
to use it inside a AXML file.
Fixes #890.

### CODE REVIEW

**Comment by azchohfi** [comment]
Anything holding the merge?

**Comment by slodge** [comment]
I think the only thing holding it up is the "nut behind the wheel" (I've not looked at it yet).

Looking at it briefly, I guess is should be good :) Although (as a task for myself) I need to remind myself how this constructor is used... every time I add one of these IntPtr constructors I find myself asking "but what happens to the private variables - how do they get instantiated?"

Will read up and remind myself again :)

**Comment by slodge** [comment]
Reading... http://developer.xamarin.com/guides/android/under_the_hood/architecture/

**Comment by slodge** [comment]
Read... but bet i have to read it again!

Thanks for the pr... sorry for the delay :)

**Comment by azchohfi** [comment]
No problem at all! Thanks for merging.
When the NuGet is updated I'll be able to use this class instead of my copied/pasted/edited one...

**Pull request merged**
