### PR TITLE
Remove bookmarks en sounds effect plugin

### PR DESCRIPTION
**Pull request by martijn00**
Fixes https://github.com/MvvmCross/MvvmCross/issues/1701 and https://github.com/MvvmCross/MvvmCross/issues/1700

### CODE REVIEW

**Comment by martijn00** [comment]
Done

**Comment by Cheesebaron** [comment]
You haven't removed those nuspecs from the build script...

**Comment by martijn00** [comment]
@Cheesebaron Where? https://github.com/MvvmCross/MvvmCross/blob/develop/build.cake#L174

I don't see them there.

**Comment by MarcBruins** [comment]
We should also remove them from the docs

**Comment by martijn00** [comment]
@MarcBruins Good point. Done!

**Comment by Cheesebaron** [comment]
Ah, I might have done it then :P move along, nothing to see here...

**Pull request merged**
