### PR TITLE
Bug fix - The async loading in the Initialize method of the first ViewModel.

### PR DESCRIPTION
**Pull request by pinkysek**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix maybe smaller refactoring. 

### :arrow_heading_down: What is the current behavior?
While using async loading in the Initialize method of the first ViewModel on UWP and iOS (maybe more except Android - Android platform is fine it using async StartUp) app remains stuck on start screen.

### :new: What is the new behavior (if this is a feature change)?
Main problem was in MvxAppStart in Start() method which is void and there was awaiter with result. https://github.com/MvvmCross/MvvmCross/blob/13eb483cd737a22b65e1e7d1b97e96b277b9a642/MvvmCross/ViewModels/MvxAppStart.cs#L28

Get result in void method is not necessary and this was probably main problem with stucked app on start. After removing GetResult() from this method Playground.UWP and Playground.iOS starts fine with async method in RootViewModel.https://github.com/MvvmCross/MvvmCross/blob/13eb483cd737a22b65e1e7d1b97e96b277b9a642/Projects/Playground/Playground.Core/ViewModels/RootViewModel.cs#L204

### :boom: Does this PR introduce a breaking change?
I don't think so.

### :bug: Recommendations for testing
None?

### :memo: Links to relevant issues/docs
Fixes - https://github.com/MvvmCross/MvvmCross/issues/3114

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by pinkysek** [comment]
Minor question how about make MvxAppStart with ConfigureAwait(false) or it's bad idea?

**Comment by Cheesebaron** [comment]
This won't work on iOS. Will throw a NSInternalInconsistencyException, since startup didn't finish before Window.MakeKeyAndVisible() was called.

**Comment by pinkysek** [comment]
> This won't work on iOS. Will throw a NSInternalInconsistencyException, since startup didn't finish before Window.MakeKeyAndVisible() was called.

Now you mean question about ConfigureAwait(false)?

**Comment by Cheesebaron** [comment]
No. Not having `StartAsync` blocking

**Comment by pinkysek** [comment]
> This won't work on iOS. Will throw a NSInternalInconsistencyException, since startup didn't finish before Window.MakeKeyAndVisible() was called.

@Cheesebaron  No this works. I did not change anything in RunAppStart method inside MvxApplicationDelegate. I made change in non-async Start() method where I removed GetResult() only. I tried this again and it works. 
 
 iOS throw NSInternalInconsistencyException only when you call StartAsync() method in RunAppStart method inside MvxApplicationDelegate. But my change is only inside MvxAppStart not in iOS platform.

 I don't know maybe I just described my commit incorrectly.

**Pull request closed without merging**
