### PR TITLE
[WIP] Speed up start process

### PR DESCRIPTION
**Pull request by Cheesebaron**
Don't pull yet...

Related to #955, #1192, #1245, #1253 and probably more.

Will probably break stuff when eventually merged.

### CODE REVIEW

**Comment by Dexyon** [comment]
Nice 👍

**Comment by Cheesebaron** [comment]
Now, making stuff async introduces some problems. Lets say we await the AndroidAsyncSetupSingleton in `OnCreate` and mark `OnCreate` `async`. This would introduce the problem that `OnResume` could potentially be called before `OnCreate` ends executing.

So I am thinking whether we should execute it sync in `OnCreate`, or does someone have a better idea what to do instead? Wrapping it in `Task.Run` wouldn't bode well, because then code can execute while system is not ready to resolve ViewModels etc.

**Comment by andyci** [comment]
I started changing the startup process to async a while ago and came across the same issue as this.  I don't think there is any other choice than to execute it synchronously because otherwise services such as the singleton cache may not be fully initialised when the viewmodels are resolved, etc.

Whilst we can make the individual methods of the setup asynchronous, I suggest we keep the InitializeAsync method synchronous as strange as that might sound.  There isn't much point in letting the user initialise the framework asynchronously and then them getting crashes when they try to use the singleton cache before it is ready

**Comment by nmilcoff** [comment]
Based on this article from Stephen Cleary https://msdn.microsoft.com/en-us/magazine/jj991977.aspx ("Configure context" subtitle, when it references figure 3)... What about setting up `OnCreate` this way:

```
private async Task DelayAsync()
{
    await Task.Delay(1000);
}

public void LifecycleMethod()
{
    // Start an async task.
    var delayTask = DelayAsync().ConfigureAwait(false);
    // Wait for it in a deadlock safe way
    delayTask.Wait();
}
```

Note that because of `ConfigureAwait(false)` before the Wait() line, it won't cause a deadlock.
Of course, this way `OnCreate` will run sync.

**Comment by nmilcoff** [comment]
If we keep a dependency to a SplashScreen and more precisely, to a method that acts as a callback like `InitializationComplete`, I think this is something possible to introduce. We could use a sandbox like this one: 

```c#
private static async void RunInSandbox(Func<Task> myTask)
{
  try
  {
    await Task.Yield();
    await myTask.Invoke();
  }
  catch (Exception ex)
  {
    ...log the exception, maybe close the app
  }
}
```
that would allow us to call `AndroidAsyncSetupSingleton` from a sync context. The call would be something like:

`TaskSandbox.RunInSandBox(() => AndroidAsyncSetupSingleton.InitializeAsync(this));`

And then just call `InitializationComplete` when the setup finishes.

**Comment by nickrandolph** [comment]
@Cheesebaron do we have a feel for where this PR is going? Given the history, we might want to open an issue linking to this PR and close it for the moment. There's some nasty pieces to the Android init (reflection searching for Setup for example) that would need an overhaul.

**Comment by Cheesebaron** [comment]
Yeah, this PR is awfully out of date. I haven't looked at this since the last comment. It ties nicely into the two PRs #2593 #2587.

**Comment by nickrandolph** [comment]
Shall we just abandon this PR and close it off then?

**Pull request closed without merging**
