### PR TITLE
Fix for contributors not appearing in docs

### PR DESCRIPTION
**Pull request by Hackmodford**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

docs update

### :arrow_heading_down: What is the current behavior?

The contributors image is blank in the documentation

### :new: What is the new behavior (if this is a feature change)?

The contributors image actually shows the contributors :)

### :boom: Does this PR introduce a breaking change?

no

### :bug: Recommendations for testing

n/a

### :memo: Links to relevant issues/docs

n/a

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [x] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Can we target this to the master branch instead please?

**Comment by Hackmodford** [comment]
Done.

If I make future doc changes, should I continue to go to develop or would you rather it go to master?

**Comment by Hackmodford** [comment]
The change was originally branched off of develop, should I branch off of master as well? (Just noticed the long commit list)

**Comment by Cheesebaron** [comment]
For docs, please use master. You might need to branch from master if you want to target master, otherwise you will pull in all the stuff from develop which haven't been released yet.

**Comment by Hackmodford** [comment]
I'll create a new PR

**Pull request closed without merging**
