### PR TITLE
Cache Java.Lang.Boolean.True since in Xamarin it results in a call

### PR DESCRIPTION
**Pull request by kjeremy**

### CODE REVIEW

**Comment by martijn00** [comment]
Do you have some more info on this, or why this is a problem?

**Comment by kjeremy** [comment]
It's just a micro opt.  Everytime you call `Java.Lang.Boolean.True` it reaches into the JNI layer and that seemed stupid for something that is static and const so I decided to cache it.

**Comment by martijn00** [comment]
Thanks for the explanation and PR!

**Comment by vvolkgang** [comment]
@kjeremy alternative explanation: https://youtu.be/9FnO3igOkOk?t=41s

**Pull request merged**
