### PR TITLE
Adding Uno v3 support

### LINKED ISSUE #3897: Uno Platform support
## 🚀 Feature Requests

Add support for Uno Platform

### Contextualize the feature

Take MvvmCross to WASM!

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms
- [ ] :🌍: Blazor

### PR DESCRIPTION
**Pull request by nickrandolph**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature - Adds support for Uno

### :arrow_heading_down: What is the current behavior?
No support for Uno

### :new: What is the new behavior (if this is a feature change)?
Additional libraries MvvmCross.Uno and MvvmCross.Uno.Plugins to support Uno

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Run the sample Uno projects

### :memo: Links to relevant issues/docs
Fixes #3897 

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [X] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
I've created a new PR that cleans up the commit history for adding Uno along with rebasing off current develop. This deprecates the older PR that I've closed (https://github.com/MvvmCross/MvvmCross/pull/3495)

**Comment by nickrandolph** [comment]
@Cheesebaron are you able to assist with getting the Sonar check to pass - seems to have an authentication error
image

**Comment by Cheesebaron** [comment]
Sonar is a separate check now, not part of the CI build. Make sure to rebase/merge develop

**Comment by nickrandolph** [comment]
@Cheesebaron we rebased yesterday so branch should be up to date. I'm still investigating the build fails but the Sonar fail appears to be authentication related (see image I attached). Is there anything I need to do to fix that?

**Comment by nickrandolph** [comment]
Woot! build success. @Cheesebaron Sonar still failing though :-(

**Comment by Cheesebaron** [comment]
Yeah Sonar fails on external branches right now. Don't worry about that.

**Comment by Cheesebaron** [comment]
Sorry for the delay @nickrandolph. This is pretty cool. We probably need to work a bit on the Presenter stuff, because some of the back navigation doesn't work. However, this should probably not prevent this work from getting in.

Some observations:
- pressing back on android using the hardware back button does nothing when you are on the first view.
- pressing close on the "Second Child View" does nothing on any platform tested
- pressing "Second Child" in the Child View on WASM does nothing

Tested Android, UWP and WASM. All of them seem to work fairly similarly. Will test iOS and macOS tomorrow-ish.

**Comment by nickrandolph** [comment]
@Cheesebaron thanks for testing this out. It might be good to get this PR in and to just mark the Uno library as prerelease. Currently we're not doing anything special for Uno, so any navigation that doesn't work will most likely be a scenario we need to add custom logic for. Let me know how you'd like to proceed.

**Comment by Cheesebaron** [comment]
@nickrandolph sure. Lets get this in. Then we can address the issues with presentation and navigation in separate issues.

Can you mark it ready for review?

**Comment by nickrandolph** [comment]
@Cheesebaron done - ping me if you need any changes as part of the review

**Comment by Cheesebaron** [comment]
Yeah, at least the conficts 😄

**Comment by nickrandolph** [comment]
@Cheesebaron argh, where'd that conflict appear from - I'll take a look when I get a chance.

**Comment by amirvenus** [comment]
> @Cheesebaron argh, where'd that conflict appear from - I'll take a look when I get a chance.

Would be great to have it merged at some point Thanks!

**Comment by Cheesebaron** [comment]
I am happy to take the contribution. As is now, it can't be merged as it doesn't build.

**Pull request closed without merging**
