### PR TITLE
#1398

### PR DESCRIPTION
**Pull request by richardblewett**
Fixed threading issue in MvxTaskBasedBindingContext where collections were being iterated over on a background thread when they could be modified on the main thread. Now take copies of the collections on the main thread before iterating over the copies in the background thread

### CODE REVIEW

**Comment by kjeremy** [comment]
It looks like the second commit removes most of the changes from the first one.  Can you squash and force push to clean this up?

I THINK this makes sense however if something is modified in the background doesn't it fall through the cracks (ie it doesn't get the change that the copy gets)?

**Comment by richardblewett** [comment]
@kjeremy I've squashed the second commit to clean up. Its only the collections that are copied, the actual bindings are not clones. 

Any inherent issue in the collections changing while the datacontext fixup takes place can be fixed by taking locks around this whole process and the register methods. Those issues were already there without this change. This change just prevents the InvalidOperationException for the collection being modified during iteration.

Would applying any existing datacontext to the binding during registration resolve the issue without locks or would that introduce other issues in the binding process?

**Comment by Cheesebaron** [comment]
Not sure how to test this. Blast through loads of binding changes on a List type of view?

**Comment by kjeremy** [comment]
@richardblewett can you rebase this on master and do a force push please?

**Comment by kjeremy** [comment]
@richardblewett not sure I follow what you mean.

**Comment by richardblewett** [comment]
@kjeremy I thought I had rebased on master and force pushed in the fork already. Are you not seeing this? Or do I need to do something in the pull request (you may have guessed I'm a little new to pull requests)

You were concerned about changes made after the copy had been taken not getting the new datacontext? If, when a binding is registered, any existing datacontext was assigned, would that solve the problem?

**Pull request merged**
