### PR TITLE
Adapt nuspecs to new structure

### PR DESCRIPTION
**Pull request by lothrop**
Still some work and testing to do here...

### CODE REVIEW

**Comment by martijn00** [comment]
Awesome!

**Comment by martijn00** [comment]
I think the files should be named like the namespace, or?

**Comment by lothrop** [comment]
@martijn00 I'm on it.

**Comment by lothrop** [comment]
Any idea if `Cirrious.MvvmCross.Droid.Maps.csproj` is being used anywhere?

**Comment by martijn00** [comment]
I've never used that one, maybe @Cheesebaron or @slodge knows?

**Pull request merged**
