### PR TITLE
Using IActivatedEventArgs in UWP

### PR DESCRIPTION
**Pull request by MartinZikmund**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

**New feature**
This PR switches the `LaunchActivatedEventArgs` class in the constructor of `MvxFormsWindowsSetup` class for the more general `IActivatedEventArgs` interface.

The app can be launched in many **other ways than just by direct launch** (URI, File association, etc.), and instead of `LaunchActivatedEventArgs` you then have an instance of different class implementing `IActivatedEventArgs` and can't therefore create `MvxFormsWindowsSetup` instance.

Internally, `MvxFormsWindowsSetup` calls `Xamarin.Forms.Forms.Init` method, which expects an instance of `IActivatedEventArgs` and doesn't require an instance of `LaunchActivatedEventArgs` specifically.

### :arrow_heading_down: What is the current behavior?

The `MvxFormsWindowsSetup` constructor requires an instance of `LaunchActivatedEventArgs`.

### :new: What is the new behavior (if this is a feature change)?

The `MvxFormsWindowsSetup` constructor expects a more general instance of `IActivatedEventArgs`.

### :boom: Does this PR introduce a breaking change?

No, because `LaunchActivatedEventArgs` implements `IActivatedEventArgs`, the new interface is just more permissive and allows other activation types like URI, File, Search and many others.

### :memo: Links to relevant issues/docs

[IActivatedEventArgs in Docs](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Activation.IActivatedEventArgs).

[LaunchActivatedEventArgs in Docs](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Activation.LaunchActivatedEventArgs).

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [x] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
Yeh I don't think we'll want to make that change in this PR but it does bode the question as to how we can improve UWP support in MVX going forward

**Comment by martijn00** [comment]
I would vote for changing this in the base too, especially since we are working on 6.0.

**Comment by MartinZikmund** [comment]
@martijn00 I will update the code to include it in the base too. Which approach sounds best to you? To pass it into the constructor and add a public `IActivatedEventArgs` property to the `MvxWindowsSetup` class?

**Comment by MartinZikmund** [comment]
I have added a new constructor to `MvxWindowsSetup` with the `IActivatedEventArgs`. Also Added new protected property `ActivationArguments` that provides access to the passed in instance if any.

**Comment by martijn00** [comment]
Looks good! Can you do a rebase?

**Comment by MartinZikmund** [comment]
@martijn00 Sorry, I was away for the weekend. Thank you for merging 👍 !

**Pull request merged**
