### PR TITLE
Delete plugins readme files (#1886)

### LINKED ISSUE #1886: Documents: Plugins README are old
Plugins README.md are old.

e.g. 
* https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-Plugins/Accelerometer/Readme.md
* latest document: https://www.mvvmcross.com/documentation/plugins/accelerometer

Proposal:
README only contains a link to the document page on mvvmcross.com.
I can PR if approved. 
Or remove them?

### PR DESCRIPTION
**Pull request by jz5**
## :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Update docs (READMEs). Fix #1886

### CODE REVIEW

**Comment by jz5** [comment]
Yes. All links are correct.

**Comment by Cheesebaron** [comment]
I am not talking about the links. But the contents of the pages the links point to.

**Comment by martijn00** [comment]
Why don't we remove all the readme files, because it should all be on the website anyways.

**Comment by jz5** [comment]
The plugins docs on mvvmcross.com are newer than readmes. And the docs contain the contents of readmes.
But  except location.md. I noticed the content of location.md is old. I copied the content from readme to location.md.

**Comment by jz5** [comment]
Delete readmes?

**Comment by martijn00** [comment]
Yes, i was thinking if we just delete all the `Readme.md`files in the plugin folders we don't need to link anymore. We already have a link to the website and documentation on the readme.md in the root folder.

**Comment by jz5** [comment]
I changed the commits to delete.

**Comment by martijn00** [comment]
Please rebase so we can merge your pr.

**Comment by jz5** [comment]
OK.
Plugins readmes had typos (#1911). But plugins documents on mvvmcross.com have no typos. (already have fixed).

**Pull request merged**
