### PR TITLE
Update Package List Documentation

### PR DESCRIPTION
**Pull request by Hackmodford**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

docs update

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by Hackmodford** [comment]
I noticed that these nugets are not mentioned.

* `MvvmCross.Platforms.Wpf`
* `MvvmCross.Forms.Platforms.Wpf`

Should they be?

**Comment by Hackmodford** [comment]
`File` and `Network` have been removed.

**Comment by Hackmodford** [comment]
Links have been added that lead to documentation for the plugins. Which points out that there are a couple that seem to be missing.

**Comment by Hackmodford** [comment]
see #4051

**Review by Cheesebaron — APPROVED** [review]

**Comment by Cheesebaron** [comment]
> I noticed that these nugets are not mentioned.
> 
>     * `MvvmCross.Platforms.Wpf`
>     * `MvvmCross.Forms.Platforms.Wpf`
> 
> Should they be?

Probably, they are needed for those respective platforms. Could be done in a separate PR.

**Comment by Hackmodford** [comment]
I added them. The description is blank because I'm not sure what they are.

**Review by Cheesebaron — APPROVED** [review]

**Comment by Cheesebaron** [comment]
Thanks!

**Pull request merged**
