### PR TITLE
Added RegisterAttribute for Mvx Views

### PR DESCRIPTION
**Pull request by maxgrig**
Added RegisterAttribute for Views for proper ACW naming in Xamarin.Android 5

### CODE REVIEW

**Comment by martijn00** [comment]
Could you use the same indentation as the source?

**Comment by maxgrig** [comment]
Fixed identation

**Comment by slodge** [comment]
:+1:

Not sure now... which of this and #965 should win?

**Comment by slodge** [comment]
I guess it was #965 

Thanks though @maxgrig :)

**Pull request closed without merging**
