### PR TITLE
Added MvxCollectionReusableView

### PR DESCRIPTION
**Pull request by PelleRavn**
Added MvxCollectionReusableView for Supplementary Elements (in other words: Sections) in UICollectionView

### CODE REVIEW

**Comment by martijn00** [comment]
Thanks!

**Comment by PelleRavn** [comment]
So I can see that the class is merged into 4.0, but not available in the 4.1.0 Nuget package. How come?

**Comment by martijn00** [comment]
I see the problem. You didn't add this class to the proj file, so it is not compiled into the nuget. I've fixed this in: https://github.com/MvvmCross/MvvmCross/commit/1552e121831f4c8eae556cd5bc4ea5aff6930999

**Comment by PelleRavn** [comment]
Oh, of course - Rookie mistake by me :) Thanks.

**Pull request merged**
