### PR TITLE
[WIP] Migrating to Shared Apple Code and Adding Support for tvOS

### PR DESCRIPTION
**Pull request by Stephanvs**
This is an initial start for migrating to the new code sharing model for Apple platforms. Also this is preferred to support the tvOS platform without duplicating a lot of code between iOS and tvOS (#1153).

# What's changed?

Most iOS targeted projects have changed from a Xamarin.iOS type of csproj to a PCL with target profile 7 (as current `Xamarin.Apple.*` nugets require). Most of the shared API surface for `UIKit` and `Foundation` are available through the reference assemblies provided by those nugets. There are however some types or members missing (mostly because of them missing in tvOS). So I'm probably still missing some required Xamarin.iOS projects that fill the last gap.

In summary this is what's done so far

- Project `MvvmCross.iOS` migrated to `MvvmCross.Apple.iOS` PCL
- Project `MvvmCross.Platform.iOS` migrated to `MvvmCross.Platform.Apple`
- Project `MvvmCross.Binding.iOS` migrated to `MvvmCross.Binding.Apple`
- Fixed some unavailable api usages. And annotated others with `#warning SHARED-APPLE` compiler directive.

# Things to do

- [ ] Figure out proper project dependency structure
- [ ] Check output paths for artefacts for new projects (for nugets)
- [ ] :microscope: Research API surface of `MvvmCross.Mac` and if it's also applicable to same shared core principle
- [ ] :hand: Support for `MvvmCross.AutoViews.iOS` -> Is this still relevant with Xamarin.Forms?
- [ ] :hand: Support for `MvvmCross.Dialog.iOS` -> Is this still relevant with Xamarin.Forms?
- [ ] :hand: Support for `CrossUI.iOS` -> Is this still relevant with Xamarin.Forms?

### CODE REVIEW

**Comment by lothrop** [comment]
Nice!

**Comment by martijn00** [comment]
Awesome start on this! I am still wondering if we shouldn't make this as separate package besides the current iOS packages?

**Comment by promontis** [comment]
Awesome!!

**Comment by jonaswisplinghoff** [comment]
Are there any plans to support watchOS in the future too? Xamarin supports watchOS 2 in the current preview, but I guess the MVVMCross integration will be more complicated than tvOS because it uses `WatchKit` instead of `UIKit`..

**Comment by Stephanvs** [comment]
Actually watchOS should be relatively easy to add after these changes

**Comment by jonaswisplinghoff** [comment]
That's great to hear! I'm currently working on my master's thesis on cross-platform smartwatch development, so maybe I can contribute on the watchOS support later on :)

**Comment by Stephanvs** [comment]
I don't think you'd want additional packages beside the current ones, because they would contain the exact same classes. It's just a different approach and I'm still trying to uncover the benefits / drawbacks of it.

**Comment by bspinner** [comment]
@Stephanvs Are you still working on this?

**Comment by Stephanvs** [comment]
Actually no, I kinda moved on to other things... sorry guys

**Comment by Cheesebaron** [comment]
No worries, we'll mark it up for grabs :)

I guess anyone who wants to look at this task talk with @Stephanvs what his thoughts about this were if the opening post does not matter.

**Comment by martijn00** [comment]
The project to unify the Apple platforms seems to be abandoned by Xamarin: https://www.nuget.org/packages/Xamarin.Apple.Core/

Let's close this for now, and see how Xamarin will move forward.

**Comment by Dexyon** [comment]
I believe Apple is not spending much time on TvOS. If you look at the App Store for TV it lacks any good updates for 6 months. So I can imagine Xamarin has stopped on it as well.

**Pull request closed without merging**
