### PR TITLE
Implemented correct behavior as for resource name generation

### PR DESCRIPTION
**Pull request by LeRondPoint**
## :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Embedded resource names did not handle special characters properly.

## :arrow_heading_down: What is the current behavior?
As documented by MS

## :boom: Does this PR introduce a breaking change?
No

## :bug: Recommendations for testing
Use the test project that was added (xUnit)

## :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Nuspec files were updated (when applicable)
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by LeRondPoint** [comment]
Fixed issue https://github.com/MvvmCross/MvvmCross/issues/1645

**Comment by Cheesebaron** [comment]
Please rebase on develop.

**Comment by LeRondPoint** [comment]
Yeah... huh damn, C#7 feature we're added yesterday and I chose not to VS2017 after 1 month of issue...  I can't make sure the propject builds...

**Comment by LeRondPoint** [comment]
https://stackoverflow.com/questions/39461407/how-to-use-c7-with-visual-studio-2015 ??

**Comment by Cheesebaron** [comment]
Please **_rebase_ (not merge)** your branch on latest develop.

**Comment by LeRondPoint** [comment]
rebased again

**Comment by LeRondPoint** [comment]
Probably fucked up the whole solution...
can't test as previously mentionned

**Comment by Cheesebaron** [comment]
You haven't done the rebase correctly.

**Comment by LeRondPoint** [comment]
Well you're going to have to be more precise because apart from selecting 'Rebase' in Sourcetree, I don't know what a "correct rebase" is supposed to mean.  I'm not a Git expert by any means... I know how to Branch, Merge and Cherry-Pick and that's about it.

**Comment by Cheesebaron** [comment]
In SourceTree:

- Check out and pull latest develop
- Switch to your own branch
- Right click develop and rebase
- Now it is important not to pull or do anything to fuck up the history
- Force push (if force push is greyed out, go to git settings and enable it)

**Comment by LeRondPoint** [comment]
When rebasing, it creates a detached HEAD, how am I supposed to push, and where?

image

**Comment by LeRondPoint** [comment]
Should be complete now

**Pull request merged**
