### PR TITLE
[WIP] Add RunOnMainThread Weaver

### LINKED ISSUE #1416: Add Method attribute to ensure to run it on the main thread
Add some attribute that ensures that the method will run on the main thread using the `IMvxMainThreadDispatcher`

### PR DESCRIPTION
**Pull request by willsb**
# :warning: This is still a work in progress, but feel free to step into the discussion and review the code :warning: 

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
This adds a weaver that detects methods annotated with the `RunOnMainThread` attribute and then makes them call the `IMvxMainThreadDispatcher`.

There are comments in `ModuleWeaver.Weave.cs` that'll make it simple for anyone to understand my approach, so there's no need to write it all down again here; reading the file should be enough to understand what's being done.

### :arrow_heading_down: What is the current behavior?
No such thing exists

### :new: What is the new behavior (if this is a feature change)?
Weavers, yay!

### :boom: Does this PR introduce a breaking change?
Not at all, just some extra sugar and magic 🍬 

### :bug: Recommendations for testing
- Extend the test cases
- Test that the warning points appear on the proper locations on errors
- Basically find corner cases where this crumbles horribly so we can
- Ideas on how to make this work even better are more than welcome

### :memo: Links to relevant issues/docs
Closes #1416

### :thinking: Checklist before submitting
- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Nuspec files were updated (when applicable)
  - [ ] We need to incorporate this weaver as a new Nuget package. If @Cheesebaron or @martijn00 could step in and do it or at least give me an overview of how packaging MvvmCross works, that would be great!
- [X] Rebased onto current develop
- [ ] Fix calls in objects that do not inherit from `MvxMainThreadDispatchingObject`<sup>1</sup>

<sup>1</sup> As you can see in the code, I simply use the existing `InvokeOnMainThread` method for classes that inherit from `MvxMainThreadDispatchingObject`. For classes that do not, I'm having a bit of a problem to weave the exact IL, though, as seen on [this diff](https://www.diffchecker.com/slO2VX6I), on line 12.

### CODE REVIEW

**Comment by martijn00** [comment]
Not sure if i see it correctly but the naming might be a bit off to our conventions. Can you name the project that will generate the nuget `MvvmCross.Weavers`?

**Comment by willsb** [comment]
_Methinks_ the Assembly needs to be named the way it is because of the way Fody works (it needs to be `WeaverName.Fody`). I don't know if dots are allowed in the name (since I have never seen a weaver that using dots in its name), this is why I went with `MvxMainThread.Fody` instead of `MvvmCross.Weavers.MainThread.Fody`. 

Maybe @SimonCropp can give me a hand here? 😄

**Comment by SimonCropp** [comment]
we only scan for `*.Fody` for perf reasons

**Comment by nickrandolph** [comment]
@willsb is this PR still moving forward? if so, can we get a rebase done and see whether we can get this finished

**Comment by willsb** [comment]
I'm working on this already in another branch, so I'll close this for the time being

**Pull request closed without merging**
