### PR TITLE
Kevinf/1880 memory leak

### PR DESCRIPTION
**Pull request by Bowman74**
## :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Removes memory leak

## :arrow_heading_down: What is the current behavior?
Android now currently and correctly maps view models from the navigator into the activity but never cleans up the cache where the view models are stored for the activity to grab when it is done loading. This has caused a memory leak that I verified with the profiler as the ViewModels mapped this way now stay in the cache forever. 

The original person who introduced the bug was correct that the cache needed to be cleaned up, it was just done it in the wrong place.

## :new: What is the new behavior (if this is a feature change)?
ViewModel is removed from the cache, removing the memory leak. The fix was verified using profiler.

## :boom: Does this PR introduce a breaking change?
No 

## :bug: Recommendations for testing
Verify view models created using NavigationService passing parameters are being cleaned up correctly.

## :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [x] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [x] Nuspec files were updated (when applicable)
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by mvanbeusekom** [comment]
This is a bit hard for me to verify, but have you made sure the bug described in issue #1880 is not reintroduced by this PR?

**Comment by Bowman74** [comment]
@mvanbeusekom Yes, I'm sure it is not been reintroduced. What caused #1880 was that the ViewModel was removed from the cache in the presenter and the activity was being loaded asynchronously. When the activity was ready it asks the views container for the ViewModel instance but it is already removed from the cache and creates a new one. The fix only removes it right after the Activity has requested to get it out out of the cache.

I do have my VSLive presentation that encountered this problem and has the solution implemented here:
https://github.com/Bowman74/VSLiveMvvmCross

It uses a custom presenter and a custom views container for Android that has the fixes in it (the current fix for #1880 in the presenter and my fix to the fix in the views container). If you remove both overrides to use the custom versions from the setup class the original #1880 problem will return when drilling down on list items. 

If you put back in just the custom presenter (with the current fix) you will see that the problem goes away but if you monitor with profiler you will also see the EditCustomerViewModel instances can never be garbage collected if you keep drilling down on list items. 

If you then add my fix you can verify the fix to #1880 still works but if you also watch with profiler you can verify that when garbage collection eventually happens the EditCustomerViewModel instances will be able to be cleaned up.

Luckily the MvvmCross ability to replace out most framework components with custom implementations make these kind of fixes easy to test. ;)

**Comment by martijn00** [comment]
@Bowman74 I think that you are right with this fix, but just to verify, https://github.com/MvvmCross/MvvmCross/pull/1871/files#diff-359ac96e4d58f2919d9c9a441b49e3dfR219 i added something to remove as well for the fragments. Should we revert that, or is it still valid?

**Comment by Bowman74** [comment]
@martijn00 We would need a sample that uses fragments to be 100% sure but I *think* we are OK, here's why. 

The code I modified is called from MvxActivityViewExtensions.OnViewCreate which applies to things of type IMvxAndroidView. That handler is only mapped if the MvxActivityViewExtensions. AddEventListeners method is called. The MvxActivity, MvxAppCompatActivity do call it in their constructors. 

The MvxCachingFragmentActivity that you modified inherits from MvxActivity but overrides that constructor, makes it protected, doesn't call into the base constructor nor calls AddEventListeners on its own. It does not appear to interact with the generic shared code I modified in any way and appears to completely have it's own management code for the ViewModels in the cache. In other words the change I made *should* not make better or worse the handling of the ViewModels in the cache used by MvxCachingFragmentActivity or be called by it in any way.

Whew, that just took me about two hours if digging through the code base to figure out what was happening and I'd say I'm only about 90% sure. I'm starting to know more about how this works under the hood that I expected. Lol.

**Comment by martijn00** [comment]
@Bowman74 The RoutingExample(https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/Navigation) contains fragments. You could use that to test.

I happy you take the time to help out. We all really appriciate it!

**Comment by Bowman74** [comment]
@martijn00 OK, it still works. The SecondHostView does call into MvxAndroidViewsContainer.TryGetEmbeddedViewModel but for whatever reason in your code there is never an embedded ViewModel key and so my new line of code is never called. I'm not sure if that is due to something specific with the example. So right now the new code doesn't interact with the code you added.

**Pull request merged**
