### PR TITLE
Synchronous resizable cells for iOS

### PR DESCRIPTION
**Pull request by MarcBruins**
This PR fixes https://github.com/MvvmCross/MvvmCross/issues/1423 for the iOS autoresizing cells. The problem is that for autoresizing to work the cells need there content, in a async situation this content may arrive later. If this happens iOS cannot estimate the size of the cell correctly and therefore it will give a faulty size. This PR check if autoresizing is on, if so it will run synchronous so iOS can do its resizing properly

### CODE REVIEW

**Comment by martijn00** [comment]
Nice work! Looks good to me!

**Comment by kjeremy** [comment]
Yikes! We should squash things like this next time :)

**Comment by RefuX** [comment]
Hi there, just ran into this issue. Any timeline on when this will make it into a release?

Thanks :)

**Comment by Cheesebaron** [comment]
I'll do one soon.

**Pull request merged**
