### PR TITLE
Implemented Group Items Observable Collection

### PR DESCRIPTION
**Pull request by thefex**
Implemented Group Items Observable Collection (INotifyCollectionChanged) support for events like: Add Item to Group, Remove Item to Group, Reset Group items.

Implements #1642

### CODE REVIEW

**Comment by thefex** [comment]
Please wait with merging that. I have just observed in one of app (HockeyApp crash log) that it has bug which could crash application.

**Comment by thefex** [comment]
Pull Request is ready to merge.

**Comment by Cheesebaron** [comment]
Not sure what is up with the build, log is empty :-/ Will see if it builds locally.

**Comment by Cheesebaron** [comment]
Build error on AppVeyor can be ignored, for this one. Changes build fine.

**Pull request closed without merging**
