### PR TITLE
App crashes on resolving IMvxFormsPagePresenter

### PR DESCRIPTION
**Pull request by vatsalyagoel**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug Fix 

### :arrow_heading_down: What is the current behavior?

When using the android on back pressed method and resolving IMvxFormsPagePresenter, it crashes with error 

```
MvxIoCContainer.Resolve (System.Type t)
MvvmCross.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.Forms.Presenters.IMvxFormsPagePresenter
MvxIoCContainer.Resolve (System.Type t)
MvxIoCContainer.Resolve[T] ()
MvxIoCProvider.Resolve[T] ()
Mvx.Resolve[TService] ()
MvxFormsAppCompatActivity+<OnBackPressed>d__30.MoveNext ()
ExceptionDispatchInfo.Throw ()
```

looking at the class it fails to register the interface type. overriding and making the change in our source code fixes the issue
### :boom: Does this PR introduce a breaking change?
No

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [x] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by vatsalyagoel** [comment]
The build passed but failed on uploading artefacts

**Comment by nickrandolph** [comment]
Thanks for submitting this PR. A couple of things:
- Have you tested other forms platforms to see if they have the same issue? I'm guessing they do
- This fix is already covered by https://github.com/MvvmCross/MvvmCross/pull/2872 across all Forms platforms. It's appreciated when submitting PRs to double-check with existing PRs to avoid duplication. 

If you can check #2872 it'd be great to get your feedback

**Comment by nickrandolph** [comment]
@martijn00 for some reason when I rebased it decided to remove MvxFormsTizenSetup.cs, but this doesn't appear in the commit history which is weird. Would you be able to assist with reverting just the removal of that file?

**Comment by vatsalyagoel** [comment]
@nickrandolph The change to tizen setup is reverted

**Comment by nickrandolph** [comment]
Thanks @vatsalyagoel

**Pull request merged**
