### PR TITLE
Add back WPF

### PR DESCRIPTION
**Pull request by martijn00**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

This still might need some changes. Pinging @onovotny to see if he can check the csproj files.

### :thinking: Checklist before submitting

- [x] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Nuspec files were updated (when applicable)
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by onovotny** [comment]
Are there XAML files in those projects?

If so, make sure you have the 1.2.1 version of the extras.

Also, at the top of each project file, you'll need this:

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/NuGetPackageExplorer.csproj#L3-L7

And at the bottom:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/NuGetPackageExplorer.csproj#L50-L51

**Comment by onovotny** [comment]
If it's just cs files, I don't think those hacks are needed. Those are necessary for the 2-pass XAML compiler in WPF

**Comment by martijn00** [comment]
No there are no XAML files in there. So we should be good to go.

**Comment by onovotny** [comment]
@martijn00, yeah, I think so. I'd make sure to use the latest extras anyway, but it should just work.

**Pull request merged**
