### PR TITLE
Add .NET 6.0 Support

### PR DESCRIPTION
**Pull request by Cheesebaron**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?
No .NET 6.0 support

### :new: What is the new behavior (if this is a feature change)?
Adds .NET 6.0 support

To do this, I had to change our usage of `WeakAttribute`. Apparently, this is not available in the net6.0-ios, net6.0-android TFMs. So the usage was changed to use WeakReference directly. Ugly code, but should behave the same.

I removed some old plugins. No one should use these unmaintained ones. Just use Xamarin Essentials instead. Especially the Location.Fused plugin gave me issues. It seems that Xamarin are building against Java.Interop 0.1.2.0 while what is bundled with .NET6.0 is Java.Interop 0.1.0.0 and binding redirects don't work.

### :boom: Does this PR introduce a breaking change?
Cleaned up TFMs plugins were built for. A lot of them do not contain code for tizen, macos and other TFMs but are built for these anyways.

YES

### :thinking: Checklist before submitting

- [x] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by Hackmodford** [comment]
If we're dropping the old plugins, I'd like to point people towards the [essential-interfaces](https://github.com/rdavisau/essential-interfaces) project. It makes it really easy to register Xamarin Essentials with the MVVMCross IoC container.

**Comment by Craige** [comment]
Any updates on this?

**Comment by Cheesebaron** [comment]
> Any updates on this?

Not really, just haven't had time to finish it up. Hopefully I will soon.

**Comment by Hackmodford** [comment]
Why is sidebar incompatible?

**Comment by Cheesebaron** [comment]
nfloat and nint usage. This was broken by Microsoft, the library needs to be rebuilt, that is not in my hands.

**Comment by Cheesebaron** [comment]
I've been struggling most of the evening getting stuff to build. However, it is simply not possible to get all the net6.0 stuff to work nicely with all the old TFMs we were supporting.

Nuking everything that isn't net6.0 for now.

**Comment by Hackmodford** [comment]
`Bye old samples`
`Byte forms`
😂

**Comment by diegostamigni** [comment]
Any update on when to get this available to test? Perhaps via alpha/beta nugets?

**Pull request merged**
