### PR TITLE
Main thread marshal

### PR DESCRIPTION
**Pull request by Cheesebaron**
As described in #1217 NotififyDataSetChanged does not always happen on the UI thread, which will result in throwing an exception.

This has been changed and removed the masking of exceptions in NotifyDataSetChanged.

### CODE REVIEW

**Comment by slodge** [comment]
Surely this shouldn't happen?

**Comment by martijn00** [comment]
Same thing should be done for the RecyclerView i think.

**Comment by slodge** [comment]
Afaik... (and my knowhow may be out of date...) there should never be updates to items in an ObservableCollection done on a background thread... it's up to the ViewModel author to work out how to avoid this - i.e. the ViewModel has to marshal the ViewModel update code to the UI thread - there is a `InvokeOnMainThread` base class method to help with this.

Posting individual changes asynchronously is dangerous - because if you start doing incremental collection changes asynchronously then it's all too easy for the UI and ViewModel to get array-out-by-one errors (or worse) - e.g. by the time the notify update message arrives in the UI that an item was inserted in position 10, then position 10 might be position 12... or it might have been deleted or...

The UI control has to be sure that the answers remain consistent when it asks GetCount, GetItemPositionAt, etc - it can't be surprised by some background thread changing the data underneath it.

There are people who've tried things to workaround this - mainly by holding two copies of the collection (one that's sync updated with the UI and one that can be manipulated on the background thread) - e.g. things like http://stackoverflow.com/a/14602121/373321 and http://www.codeproject.com/Articles/183495/Asynchronous-Multi-threaded-ObservableCollection - and I think some of the newer Windows controls have special options to allow them to update asynchronously... but none of this for Droid or iOS (yet?)

**Comment by Cheesebaron** [comment]
Hmm you might be on to something here. I know for sure properties in a MvxNotifyPropertyChanged type of model, when RaisePropertyChanged is called is marshalled to the UI thread per default. So I guess we have to make it super clear when using ObservableCollection or derivatives that it is up to the dev to fix that themselves.

**Comment by slodge** [comment]
Here's an old Q&A on it - http://stackoverflow.com/a/18469700/373321

**Pull request closed without merging**
