### PR TITLE
Removed Fragging and FullFragging

### PR DESCRIPTION
**Pull request by martijn00**

### CODE REVIEW

**Comment by martijn00** [comment]
Fix for: https://github.com/MvvmCross/MvvmCross/issues/1011

**Comment by martijn00** [comment]
@slodge What do you think of this? Should we move forward and remove this stuff? Everything should be compatible with https://github.com/MvvmCross/MvvmCross-AndroidSupport we only need to warn people that they have to fix the packages to the new nugets

**Comment by martijn00** [comment]
@JoeCooper Yes it is now in: https://github.com/MvvmCross/MvvmCross-AndroidSupport

We will make some explanations on this later.

**Comment by lothrop** [comment]
@martijn00 FullFragging is still there... Is that intentional?

**Comment by martijn00** [comment]
@lothrop yes. due to requests of users of full fragging we added it again.

**Pull request merged**
