### PR TITLE
Tab presenter for WPF and update Playground to demonstrate(New)

### PR DESCRIPTION
**Pull request by yanxiaodi**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Add tab presenter for WPF and update Playground to demonstrate
Original things from @benhysell @Happin3ss .

### :arrow_heading_down: What is the current behavior?
No tab presenter for WPF

### :new: What is the new behavior (if this is a feature change)?
New tab presenter for WPF

### :boom: Does this PR introduce a breaking change?
No.

### :memo: Links to relevant issues/docs
#2712 
#2765 

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [x] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by yanxiaodi** [comment]
@Cheesebaron @martijn00 could you please review this PR? Thanks.

My question is if we should only allow the `MvxWindowView` to be the container of the `TabControl`? If it is not necessary, I can update it to support the `MvxWpfView `.

**Comment by tuke307** [comment]
Nice implementation without setting the Content Control over the CreateViewPresenter. But how do you  register that Custom View implementation in the Setup?

**Comment by yanxiaodi** [comment]
@tuke307 have you tested the `Playground.WpfCore` project in this PR?

**Comment by tuke307** [comment]
No i wrote extra classes and inherit the base classes. But i have to Register this :(

**Comment by yanxiaodi** [comment]
@tuke307 I think you could try the playgournd project in the PR. That is an out-of-box sample you can run. The PR may not cover all the scenarios and welcome for any feedback.

**Review by Sem1712 — APPROVED** [review]

**Comment by yanxiaodi** [comment]
Not sure why the Sonar pipeline failed. Can anyone please have a look? Thanks.

**Pull request closed without merging**
