### PR TITLE
Merge Sub repos into main repo

### PR DESCRIPTION
**Pull request by martijn00**

### CODE REVIEW

**Comment by Cheesebaron** [comment]
This is for #1500 

Also, while you are doing this. It would be great to fix references so they are not dependent on NuGet packages for the sub repos.

**Comment by martijn00** [comment]
Yes! I'm working on fixing the references!

**Comment by kjeremy** [comment]
My gut says that we need to move more around.

Having top level directories `MvvmCross-Forms`, `MvvmCross-AndroidSupport`, `MvvmCross-iOSSupport`, `MvvmCross-Plugins` is good. Then I think we may need a `MvvmCross` directory that has most of the other directories: `MvvmCross`, `Cirrious`, the solution files etc.

**Comment by kjeremy** [comment]
Looks like it preserves the history too even if it's a bit crazy.  Not sure about tags etc though.

**Comment by martijn00** [comment]
@kjeremy what do you mean with the structure? It already is like that after this PR?

**Comment by kjeremy** [comment]
My bad.  I have some stale directories

**Pull request merged**
