### PR TITLE
Add netcoreapp3.0 support

### LINKED ISSUE #3355: Any supports to WPF on .NET Core 3.0?
## 🚀 Feature Requests

I'm trying to use .NET Core 3.0 as the framework for WPF. Currently, it is preview but I'm wondering if we can add the WPF .NET Core 3.0 support to MvvmCross? 

### Describe the feature
WPF with .NETCore 3.0 has better performance.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

Thanks all.

### PR DESCRIPTION
**Pull request by mgochmuradov**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?
.NET Core 3.0 is not supported

### :new: What is the new behavior (if this is a feature change)?
- Added netcoreapp3.0 target to MvvmCross
- Added WPF .NET Core 3 sample

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Check the WpfCore playground

### :memo: Links to relevant issues/docs
Fixes #3355

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by mgochmuradov** [comment]
It is building and running locally, but DevOps fails to build the Playground.WPFCore project, Maybe needs to add netcore3.0 build support in build script.

**Comment by Cheesebaron** [comment]
You seem to have included the WpfCore project in the Release configuration. None of the other samples or playground project are built in that configuration. So the build is failing:

```
       "D:\a\1\s\Projects\Playground\Playground.WpfCore\Playground.WpfCore.csproj" (default target) (47) ->
       (MarkupCompilePass1 target) -> 
         D:\a\1\s\Projects\Playground\Playground.WpfCore\Views\ChildView.xaml(2,19): error MC6028: x:TypeArguments="vm:ChildViewModel" is not valid. 'vm:ChildViewModel' is not a valid type name reference for the generic argument at position '1'. Line 2 Position 19. [D:\a\1\s\Projects\Playground\Playground.WpfCore\Playground.WpfCore.csproj]
         D:\a\1\s\Projects\Playground\Playground.WpfCore\Views\ModalView.xaml(2,19): error MC6028: x:TypeArguments="vm:ModalViewModel" is not valid. 'vm:ModalViewModel' is not a valid type name reference for the generic argument at position '1'. Line 2 Position 19. [D:\a\1\s\Projects\Playground\Playground.WpfCore\Playground.WpfCore.csproj]
         D:\a\1\s\Projects\Playground\Playground.WpfCore\Views\NestedModalView.xaml(2,19): error MC6028: x:TypeArguments="vm:NestedModalViewModel" is not valid. 'vm:NestedModalViewModel' is not a valid type name reference for the generic argument at position '1'. Line 2 Position 19. [D:\a\1\s\Projects\Playground\Playground.WpfCore\Playground.WpfCore.csproj]
         D:\a\1\s\Projects\Playground\Playground.WpfCore\Views\SecondChildView.xaml(2,19): error MC6028: x:TypeArguments="vm:SecondChildViewModel" is not valid. 'vm:SecondChildViewModel' is not a valid type name reference for the generic argument at position '1'. Line 2 Position 19. [D:\a\1\s\Projects\Playground\Playground.WpfCore\Playground.WpfCore.csproj]
         D:\a\1\s\Projects\Playground\Playground.WpfCore\Views\WindowChildView.xaml(2,19): error MC6028: x:TypeArguments="vm:WindowChildViewModel" is not valid. 'vm:WindowChildViewModel' is not a valid type name reference for the generic argument at position '1'. Line 2 Position 19. [D:\a\1\s\Projects\Playground\Playground.WpfCore\Playground.WpfCore.csproj]
         D:\a\1\s\Projects\Playground\Playground.WpfCore\Views\WindowView.xaml(2,18): error MC6028: x:TypeArguments="vm:WindowViewModel" is not valid. 'vm:WindowViewModel' is not a valid type name reference for the generic argument at position '1'. Line 2 Position 18. [D:\a\1\s\Projects\Playground\Playground.WpfCore\Playground.WpfCore.csproj]
```

**Comment by mgochmuradov** [comment]
> You seem to have included the WpfCore project in the Release configuration. None of the other samples or playground project are built in that configuration. So the build is failing:

@Cheesebaron I haven't explicitly included WpfCore projects in Release configuration, and not sure how to remove them from Release configuration. I could fix it if you tell me where are these configurations.

**Comment by Cheesebaron** [comment]
@mgochmuradov new projects are most likely added to all configurations. They are in the Solution File.

In VS 4 mac, you can configure those from: **Project -> Solution Options -> Configurations**
in VS for Windows, you can find these in target drop down box.

**Pull request merged**
