### PR TITLE
Enable methods of MvxExpandableListAdapter to allow Overwritten.

### PR DESCRIPTION
**Pull request by viniciusmaia**
I had a situation in application that I needed customize my MvxExpandableListView and I can't did it, because the methods in MvxExpandableListAdapter can't be overwritten.

I suggest that you enable overwritten of MvxExpandableListAdapter making them virtual. In other  words, replace this:

 public View GetGroupView(int groupPosition, bool isExpanded, View convertView, ViewGroup parent)

for this:

 public virtual View GetGroupView(int groupPosition, bool isExpanded, View convertView, ViewGroup parent)

for all methods in MvxExpandableListAdapter.

That's the current class: https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Binding/Droid/Views/MvxExpandableListAdapter.cs#L21

Sorry for english errors. I'm brazilian and my english is limited.

### CODE REVIEW

**Comment by kjeremy** [comment]
I think you may have messed up your git history here.

**Comment by Cheesebaron** [comment]
Please rebase your changes on the develop branch. Not sure what has happened with your history.

**Comment by jamie94bc** [comment]
😮

**Comment by viniciusmaia** [comment]
I didn't developed anything. It's just a suggestion for an improvement in MvvmCross for Android.

**Comment by jamie94bc** [comment]
So this is supposed to be an issue not a pull request? 😕

**Comment by viniciusmaia** [comment]
First, suggest this with an issue and a developer talked to create a pull request for this.

**Pull request closed without merging**
