### PR TITLE
#1921 Changed wpf implementation to use view model parameter sent wit…

### PR DESCRIPTION
**Pull request by Bowman74**
…h request by new navigation service. Updated wfp event hooks sample application to be more complete.

## :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug Fix

## :arrow_heading_down: What is the current behavior?
When using the new navigation service the view model created with the request is ignored, instead the original ShowViewModel behavior is used creating a second view model ignoring the one from the request that has the parameter passed to it.

## :new: What is the new behavior (if this is a feature change)?
Only one view model is created when the new navigation service is used and the parameter properly passed to it.

## :boom: Does this PR introduce a breaking change?
No

## :bug: Recommendations for testing
Test in a variety of scenarios for navigation. I tested about three of the many possible scenarios

## :memo: Links to relevant issues/docs
#1921, #1943 

## :thinking: Checklist before submitting

- [x] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Nuspec files were updated (when applicable)
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
We're seeing a similar problem with using Master-Details in a Forms app when navigating between details pages. An alternative to this implementation is to move the check for existing view model into the LoadViewModel method - this would fix this issue for all platforms.

**Comment by martijn00** [comment]
@nickrandolph Hmm you might be right about that one! We have to look into it.

**Comment by nickrandolph** [comment]
I just tried this, which seems to solve this issue (in MvxPresenterHelpers), but this is specific to Mvvmcross for Forms. Wonder if it could be pushed into the viewModelLoader?

public static IMvxViewModel LoadViewModel(MvxViewModelRequest request)
{
    if (request is MvxViewModelInstanceRequest instance) return instance.ViewModelInstance
    var viewModelLoader = Mvx.Resolve<IMvxViewModelLoader>();
    var viewModel = viewModelLoader.LoadViewModel(request, null);
    return viewModel;
}

**Comment by Bowman74** [comment]
@nickrandolph That would not work for all platforms. Not all platforms can pass the request instance to the view and instead keep the view model in a cache location that needs to be handled completely differently with the position in the cache passed to the view instead (UWP and Android both have variations on this).

**Comment by nickrandolph** [comment]
Yep fair enough. I didn't have time to do a full test on that suggestion (hence no pull request). 

This issue is actually pretty severe as it is completely screwing up navigation on Forms using Master Details. You can see this if you attempt to navigate to a different view model from one of the details view models in the forms master-detail sample project

**Comment by Bowman74** [comment]
Unfortunately about to board a flight. I can look at that problem later. I suspect there may be a custom presenter in play that may need modification. Can you send me a link to the sample (just to be sure we are looking at the same one)?

**Comment by Bowman74** [comment]
@nickrandolph, I do not see a master detail example under TestProjects\Forms\ directory for WPF? Is there some WPF example in another location? Nor do I even find any MvvmCross support for Forms in general for WPF?

If not this PR only impacts WPF and is intended to fix a WFP specific bug so any separate issues should likely be handled under another issue.

**Comment by Cheesebaron** [comment]
There is no WPF support from Xamarin.Forms to begin with. So dunno how what @nickrandolph talks about relates to this issue.

**Comment by kjeremy** [comment]
Not yet, but I believe they're working on it https://github.com/xamarin/Xamarin.Forms/pull/895

**Comment by Cheesebaron** [comment]
@kjeremy well still not related to this issue though. @nickrandolph if you have an issue with Forms, make a new issue and just link to this.

**Comment by nickrandolph** [comment]
I'll raise another issue later today but my observation stands. The issue which is fixed by this commit seems to be mirrored (and admittedly I don't know the code base well enough to know whether the root cause is the same) by breaking functionality when using Mvvmcross for forms with master detail.

**Comment by Bowman74** [comment]
@nickrandolph Yes a new issue would be great. If you look at what files this commit changes they are all in WPF specific projects which are not used for the Forms projects in any way, shape or form.

**Pull request merged**
