### PR TITLE
Updating various startup logic

### PR DESCRIPTION
**Pull request by nickrandolph**
I've started going through various pieces of startup logic. My concern is that Android isn't starting correctly but VS is being a pain and I haven't been able to even step through the logic successfully.

### CODE REVIEW

**Comment by nickrandolph** [comment]
@Cheesebaron hey sorry about being a bit absent, where's this set of changes at now? Let me know what it's waiting on and I can help finish it.

**Comment by nickrandolph** [comment]
@Cheesebaron hey sorry about being a bit absent, where's this set of changes at now? Let me know what it's waiting on and I can help finish it.

**Comment by Cheesebaron** [comment]
I merged it into my branch here: https://github.com/MvvmCross/MvvmCross/pull/2587

**Comment by nickrandolph** [comment]
@Cheesebaron I was chatting with @martijn00 about this and we concluded we'd wait for after v6 is baked before we pursue this.

**Comment by Cheesebaron** [comment]
I don't disagree. It also needs to be tested well, so we don't encounter new gremlins by making it asynchronous.

**Pull request merged**
