### PR TITLE
Move Mvx class into IoC

### PR DESCRIPTION
**Pull request by martijn00**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Cleanup

### :arrow_heading_down: What is the current behavior?

Mvx static class is basically just duplicating the IoC provider class

### :new: What is the new behavior (if this is a feature change)?

Duplicates gone

### :boom: Does this PR introduce a breaking change?

Yes, only renaming.

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
Hmmm, this touches sooo many files - can we at least get my PRs through so I don't have to fix them all  :-)

**Comment by Cheesebaron** [comment]
You are not done it seems:

```
Platforms\Android\Views\MvxFormsApplicationActivity.cs(179,33): error CS0117: 'Mvx' does not contain a definition for 'Resolve' [C:\projects\mvvmcross\MvvmCross.Forms\MvvmCross.Forms.csproj]
```

**Comment by nickrandolph** [comment]
tbh I'd like to see the existing methods marked as deprecated and give devs the opportunity to change their code before we break everyone

**Comment by nmilcoff** [comment]
I pretty much agree with Nick. Although this is a very cool change, we can wait a bit before breaking everyone's code

**Comment by martijn00** [comment]
I've fixed the error and marked the methods as obsolete so we can remove them in the next version.

**Comment by nickrandolph** [comment]
Fixed code factor issues - the remaining ones are either duplicate code (unavoidable) and multiple classes in same file (by design in mvvmcross for generic class in same file as non-generic class).
@martijn00 @Cheesebaron @nmilcoff  you good to merge this?

**Pull request merged**
