### PR TITLE
MultiRegionViewPresenter - Support frame search failure.

### PR DESCRIPTION
**Pull request by ErezG**
Upon search failure (no matching frame found), use the default frame.

It allows flexability in building a responsive app that navigates to a frame on big screens and navigates inside the main frame if the screen is small.

### CODE REVIEW

**Comment by martijn00** [comment]
Please use the same formatting so it is easier to see what changed.

**Comment by ErezG** [comment]
Martin,
So what now? is there a problem with the PR?

**Comment by martijn00** [comment]
It seems good to me now, but i haven't used this functionality yet. Maybe @Stephanvs, @ErezG or @pauloapsantos knows?

**Comment by ErezG** [comment]
I've used it and it works. This change comes from the adjustment I had to do in my project.

**Pull request merged**
