### PR TITLE
MvxNavigationService.cs. Add "throw" for an exception in the method NavigationRouteRequest.

### PR DESCRIPTION
**Pull request by kvandake**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Adding error throw in the method NavigationRouteRequest.

### :arrow_heading_down: What is the current behavior?
Do not throw an exception in any navigation facade.

### :new: What is the new behavior (if this is a feature change)?
Adds an error throw when an error is caused in any navigation facade.

### :boom: Does this PR introduce a breaking change?
No.

### :bug: Recommendations for testing
Adds an error throw in any navigation facade.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Please reopen this on develop instead.

**Comment by kvandake** [comment]
Why? Then the master will not merge into the develop?

**Comment by Cheesebaron** [comment]
We are using git flow, that is why.

**Comment by kvandake** [comment]
Ok, I understood. I created pull request by [develop](https://github.com/MvvmCross/MvvmCross/pull/2651).

**Pull request merged**
