### PR TITLE
Code factor style issues fix

### PR DESCRIPTION
**Pull request by Prandtl**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Code factor styling issues fix for #1922 
### :boom: Does this PR introduce a breaking change?
No
### :thinking: Checklist before submitting

- [ ] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Nuspec files were updated (when applicable)
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by Prandtl** [comment]
Don't really know what to do about code duplication issues: the code duplication is mostly in Droid controls and I don't see a nice way and a reason to remove this duplication. If there are no suggestions this can be merged.

**Comment by martijn00** [comment]
Can you make sure to use spaces instead of tabs?

**Comment by Prandtl** [comment]
Changed tabs to spaces.

**Comment by martijn00** [comment]
Some are still tabs. After that is fixed i think this is good to merge.

**Comment by Prandtl** [comment]
OK, done. By the way, how do you check PR if it is spaces only?

**Pull request merged**
