### PR TITLE
Create view events in Viewmodels

### PR DESCRIPTION
**Pull request by martijn00**
This enables devs to do stuff in their viewmodel on certain lifecycle events

### CODE REVIEW

**Comment by Cheesebaron** [comment]
If you are wondering why it does not build.

```
[00:04:45] "C:\projects\mvvmcross\MvvmCross_All.sln" (Build target) (1) ->
[00:04:45] "C:\projects\mvvmcross\MvvmCross\Windows\Wpf\MvvmCross.Wpf.csproj" (default target) (138) ->
[00:04:45] (CoreCompile target) -> 
[00:04:45]   Views\MvxWpfView.cs(37,23): error CS1061: 'IMvxViewModel' does not contain a definition for 'Disappearing' and no extension method 'Disappearing' accepting a first argument of type 'IMvxViewModel' could be found (are you missing a using directive or an assembly reference?) [C:\projects\mvvmcross\MvvmCross\Windows\Wpf\MvvmCross.Wpf.csproj]
[00:04:45]   Views\MvxWpfView.cs(38,23): error CS1061: 'IMvxViewModel' does not contain a definition for 'Disappeared' and no extension method 'Disappeared' accepting a first argument of type 'IMvxViewModel' could be found (are you missing a using directive or an assembly reference?) [C:\projects\mvvmcross\MvvmCross\Windows\Wpf\MvvmCross.Wpf.csproj]
[00:04:45]   Views\MvxWpfView.cs(43,23): error CS1061: 'IMvxViewModel' does not contain a definition for 'Appearing' and no extension method 'Appearing' accepting a first argument of type 'IMvxViewModel' could be found (are you missing a using directive or an assembly reference?) [C:\projects\mvvmcross\MvvmCross\Windows\Wpf\MvvmCross.Wpf.csproj]
[00:04:45]   Views\MvxWpfView.cs(44,23): error CS1061: 'IMvxViewModel' does not contain a definition for 'Appeared' and no extension method 'Appeared' accepting a first argument of type 'IMvxViewModel' could be found (are you missing a using directive or an assembly reference?) [C:\projects\mvvmcross\MvvmCross\Windows\Wpf\MvvmCross.Wpf.csproj]
[00:04:45] 
[00:04:45] 
[00:04:45] "C:\projects\mvvmcross\MvvmCross_All.sln" (Build target) (1) ->
[00:04:45] "C:\projects\mvvmcross\TestProjects\Eventhooks\Eventhooks.Core\Eventhooks.Core.csproj" (default target) (139) ->
[00:04:45]   ViewModels\FirstViewModel.cs(10,24): error CS0115: 'FirstViewModel.Appearing()': no suitable method found to override [C:\projects\mvvmcross\TestProjects\Eventhooks\Eventhooks.Core\Eventhooks.Core.csproj]
[00:04:45]   ViewModels\FirstViewModel.cs(15,24): error CS0115: 'FirstViewModel.Appeared()': no suitable method found to override [C:\projects\mvvmcross\TestProjects\Eventhooks\Eventhooks.Core\Eventhooks.Core.csproj]
[00:04:45]   ViewModels\FirstViewModel.cs(20,24): error CS0115: 'FirstViewModel.Disappearing()': no suitable method found to override [C:\projects\mvvmcross\TestProjects\Eventhooks\Eventhooks.Core\Eventhooks.Core.csproj]
[00:04:45]   ViewModels\FirstViewModel.cs(25,24): error CS0115: 'FirstViewModel.Disappeared()': no suitable method found to override [C:\projects\mvvmcross\TestProjects\Eventhooks\Eventhooks.Core\Eventhooks.Core.csproj]
```

**Comment by kjeremy** [comment]
How will these event hooks work wrt things like list items?  Should we modify our adapters/viewholders or are these more of a 'page' level concept?

**Comment by martijn00** [comment]
For now it's more a page level concept. This is more something i think we should integrate because i see a lot of projects implementing something like this on their own. We just start on this now, and could be improved by more PR's later on. 

As also explained in this post for Xamarin Forms, this is not going to cover 100% but at least helps a lot for now.

**Comment by Cheesebaron** [comment]
Still had issues building this on my machine, getting the same errors as the CI does. Rebuilding after it failed worked though.

Not sure what is going on, but I find it strange that it couldn't find the newly added methods on the `IMvxViewModel` interface.

**Pull request merged**
