### PR TITLE
Clean up some long time obsolete API's

### PR DESCRIPTION
**Pull request by Plac3hold3r**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Clean up

### :arrow_heading_down: What is the current behavior?

Some API code marked as obsolete has survived through multiple major MvvmCross version updates. With v6 being a major version change perhaps now it the time to remove them.

### :new: What is the new behavior (if this is a feature change)?

🔥🔥🔥

### :boom: Does this PR introduce a breaking change?

Yes, if projects are still using the API's

Removed `MvxFluentBindingDescription.cs` method marked obsolete [v3.5.0-alpha](https://github.com/MvvmCross/MvvmCross/commit/c6993fdd057f29bc107b2750796d43668c711013)

```C#
protected void Overwrite(MvxBindingDescription bindingDescription);
public MvxFluentBindingDescription<TTarget, TSource> Described(string bindingDescription);
public MvxFluentBindingDescription<TTarget, TSource> Described(MvxBindingDescription description);
public MvxFluentBindingDescription<TTarget> Described(string bindingDescription);
public MvxFluentBindingDescription<TTarget> Described(MvxBindingDescription description);
```

Removed `tvOS/Views/MvxCollectionViewCell.cs` ctor marked obsolete [v4.4.0](https://github.com/MvvmCross/MvvmCross/commit/f1cf5dfcef282e0ed577cffa9c5eaf6f0953b4d2#diff-840591e1d9e2358f19e29e7ecb535d37)

```C#
public MvxCollectionViewCell(IntPtr handle, string bindingText) : this(bindingText, handle);
public MvxCollectionViewCell(CGRect frame, string bindingText) : this(bindingText, frame);
public MvxCollectionViewCell(CGRect frame, IEnumerable<MvxBindingDescription> bindingDescriptions) : this(bindingDescriptions, frame);
```

Removed `MvxIoCExtensions.cs` class and dependencies marked obsolete [v3.0.9](https://github.com/MvvmCross/MvvmCross/commit/ea9ab7f98634880ea1c6b1a194406b92c123081b#diff-0e83b7018e956d1dc528efbb8729ecd5R12)

- `IMvxConsumer.cs`
- `IMvxProducer.cs`

Removed `MvxTabActivity.cs` class and dependencies marked obsolete [v4.2.0](https://github.com/MvvmCross/MvvmCross/commit/c9be4b304c9c4b84f1a0d18be67075b6123d6d87#diff-b62d22275caf8e87c6fb66a64dc60329)
- `MvxEventSourceTabActivity.cs`

### :bug: Recommendations for testing

n/a

### :memo: Links to relevant issues/docs

n/a

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [X] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [X] Rebased onto current develop

### CODE REVIEW

**Comment by Plac3hold3r** [comment]
A possible additional item to remove is the Android `MvxTabActivity`. It was marked as obsolete in MvvmCross [v4.2.0 (June 4, 2016)](https://github.com/MvvmCross/MvvmCross/commit/c9be4b304c9c4b84f1a0d18be67075b6123d6d87#diff-b62d22275caf8e87c6fb66a64dc60329). As the Android TabActivity became obsolete in favor of the ViewPager.

**Comment by martijn00** [comment]
Sounds good to remove the tab activity too.

**Comment by Plac3hold3r** [comment]
I'm just looking through some others there is also, `MvxIoCExtensions.cs` which was marked as obsolete way back with [v3.0.9 (Feb 24, 2013)](https://github.com/MvvmCross/MvvmCross/commit/ea9ab7f98634880ea1c6b1a194406b92c123081b#diff-0e83b7018e956d1dc528efbb8729ecd5R12). Perhaps we can also nuke that? It seems it relates to a older pattern for the IoC resolving before the `Mvx` static class was introduced.

**Comment by Plac3hold3r** [comment]
I think this should be good for review and merge. 

The only other out standing obsolete attributes are being use to get user to use the generic parameters of IMvxCommand.

**Pull request merged**
