### PR TITLE
Create MvxUIActivityIndicatorViewHiddenTargetBinding

### PR DESCRIPTION
**Pull request by munkii**
The default binding for UIActivityIndicatorView Hidden will only show\hide the view. It needs to be told to spin and that is not a property it is a method. This binding does that calling of the appropriate method as well as the setting of Hidden

### CODE REVIEW

**Comment by lothrop** [comment]
Thanks, this looks like something I could have used in the past.

The file ending `.cs` is missing and the file isn't referenced in any `.csproj` file. Could you please fix those two things?

**Comment by munkii** [comment]
That'll teach me to copy and paste out of our project, sorry

**Comment by munkii** [comment]
Done

**Comment by Cheesebaron** [comment]
Why is this in the 3.2 branch?

**Comment by munkii** [comment]
That was the branch I had forked when I was last making updates. My GitHub skills are bloody terrible. I can Fork the latest if you want and add it there. Probably won't be until Monday now

**Comment by Cheesebaron** [comment]
There is no reason to add it to the 3.2 branch, it isn't even the main branch. How you got it tangled into that branch I have no idea. This goes into 4.0.

**Pull request closed without merging**
