### PR TITLE
Added generic versions of MvxApplication for WPF and UWP

### PR DESCRIPTION
**Pull request by nmilcoff**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Probably a feature, or a fix?

### :arrow_heading_down: What is the current behavior?
Classes with generic versions on most platforms. But UWP and WPF are missing

### :new: What is the new behavior (if this is a feature change)?
Above is fixed.

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
/

### :memo: Links to relevant issues/docs
Previous PR: #2668 

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [X] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
Interesting - I could have sworn that I tried this and had issues with Visual Studio not building with a generic Application class. Can you make sure resources defined in App.xaml can be loaded correctly - I won't get to it tonight but can add to this PR tomorrow morning if you want

**Comment by nickrandolph** [comment]
Also, if this works, we should be able to do the same for the XF UWP application class too

**Comment by nmilcoff** [comment]
Sure, I'll test that later today. I'm not really a UWP/WPF expert so any help here will be much appreciated @nickrandolph 🙂

**Comment by nickrandolph** [comment]
As I suspected this gives a build error for the Playground.Uwp project:
7>C:\Source\github\btr-mvx\Projects\Playground\Playground.Uwp\App.xaml.cs(7,33,7,36): error CS0263: Partial declarations of 'App' must not specify different base classes
Resolving this would require changing the App.xaml to use the generic base class but that's not supported in UWP (XF has generics support in XAML but not UWP currently).
I've pushed one option for fixing this. 
The other (much less desirable) is to remove the App.xaml. This is fine, until you want to register application wide static resources... I would not recommend this approach

**Pull request merged**
