### PR TITLE
Migrate to Net Standard for PCL projects

### PR DESCRIPTION
**Pull request by martijn00**
TODO:
- [ ] Update nuspecs to follow .NET Standard
- [ ] Fix CodeAnalysis package to follow Standard
- [ ] Update Plugins and dependencies

### CODE REVIEW

**Comment by azchohfi** [comment]
This is a Major change, since it limits VS version, because of NuGet versioning. It proooobably will work, buuuuut it's something to consider.
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#required-tools

For example, you can't use this on XS just yet.

**Comment by Cheesebaron** [comment]
Does it really matter that much which version of VS is supported?

**Comment by kjeremy** [comment]
I would say so, considering they don't ship Xamarin Studio on Windows
anymore.

**Comment by Cheesebaron** [comment]
But Visual Studio Community edition is free? If a big company making more than allowed in Community edition, can't be arsed to get a newer version, should we _really_ care?

**Comment by azchohfi** [comment]
Yes, it is free, but not for enterprise(5+ employee). They need to use Professional or Enterprise editions of VS.

**Comment by lothrop** [comment]
This would mean that all users of MvvmCross would have switch their PCL projects to Net Standard?

**Comment by azchohfi** [comment]
No, they can still use the PCL profile they are already using, but they can change to netstandard if they want to. That's the beauty of it ;)

**Comment by Costo** [comment]
Xamarin Studio now supports NetStandard libraries: https://blog.xamarin.com/net-standard-library-support-for-xamarin/

**Comment by Cheesebaron** [comment]
Why did you remove WindowsCommon? Only WinPhone 8.0/8.1 silverlight should be removed. WindowsCommon/WindowsStore/WindowsPhone in non silverlight variants should stay. Especially WindowsCommon as that code is used in UWP a lot of places.

**Comment by martijn00** [comment]
I've updated the PCL projects to NetStandard 1.4 and that doesn't support WindowsStore/WindowsPhone in non silverlight variants either. I should readd the WindowsCommon to UWP tho.

**Comment by Cheesebaron** [comment]
Well... To have support for Windows Phone we need to use .NET Standard 1.2.

I wonder how many people still use MvvmCross for Windows Phone 8.1 apps.

**Comment by jimbobbennett** [comment]
Is this still on the roadmap? Would be good to have .Net standard support in MvvmCross 4

**Comment by Cheesebaron** [comment]
It is still on the roadmap. Just need someone to finish the grunt work.

**Comment by kjeremy** [comment]
I would prefer holding off on netstandard for at least one more release
until the tooling is a little better.

**Comment by promontis** [comment]
@kjeremy what do miss/is not working in the current tooling?

**Comment by kjeremy** [comment]
I would wait until vs15 is released since that's really when netstandard is
going to make its debut.  Personally I have converted two of my projects to
netstandard and they both fail to find references.  Then you have to go in
and muck with the json to consume pcls... I just haven't had a good
experience yet and I want that conversion process working before the
switch.  They are also moving the project format back to XML and I'm not
sure thats in the tooling yet though I could be wrong.

**Comment by smstuebe** [comment]
I switched my fingerprint plugin to netstandard and keep getting github issues, where people can't use it because of a missing Visual Studio update.  I hope the tooling will be stable, soon. :/

**Comment by Cheesebaron** [comment]
@smstuebe yea, tooling isn't the greatest right now.

**Comment by tofutim** [comment]
how close on we on netstandard11?

**Comment by Cheesebaron** [comment]
@tofutim we are not going to do 1.1, but 2.0. Technically 1.1 should be already be supported.

**Comment by tofutim** [comment]
I think technically yes, but if I create a new netstandard11 PCL and try to
add MvvmCross, this is what happens:

```
Package MvvmCross.Core 4.4.0 is not compatible with netstandard1.1
(.NETStandard,Version=v1.1). Package MvvmCross.Core 4.4.0 supports:
  - dotnet (.NETPlatform,Version=v5.0)
  - monoandroid (MonoAndroid,Version=v0.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore45 (.NETCore,Version=v4.5)
  - portable-net45+win8+wp8+wpa81
(.NETPortable,Version=v0.0,Profile=Profile259)
  - portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32)
  - uap (UAP,Version=v0.0)
  - win81 (Windows,Version=v8.1)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos (Xamarin.TVOS,Version=v0.0)
Package MvvmCross.Binding 4.4.0 is not compatible with netstandard1.1
(.NETStandard,Version=v1.1). Package MvvmCross.Binding 4.4.0 supports:
  - dotnet (.NETPlatform,Version=v5.0)
  - monoandroid (MonoAndroid,Version=v0.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore45 (.NETCore,Version=v4.5)
  - portable-net45+win8+wp8+wpa81
(.NETPortable,Version=v0.0,Profile=Profile259)
  - portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32)
  - win81 (Windows,Version=v8.1)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos (Xamarin.TVOS,Version=v0.0)
Package MvvmCross.Platform 4.4.0 is not compatible with netstandard1.1
(.NETStandard,Version=v1.1). Package MvvmCross.Platform 4.4.0 supports:
  - dotnet (.NETPlatform,Version=v5.0)
  - monoandroid (MonoAndroid,Version=v0.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore45 (.NETCore,Version=v4.5)
  - portable-net45+win8+wp8+wpa81
(.NETPortable,Version=v0.0,Profile=Profile259)
  - portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32)
  - win81 (Windows,Version=v8.1)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos (Xamarin.TVOS,Version=v0.0)
One or more packages are incompatible with .NETStandard,Version=v1.1.
Package restore failed for 'Loqu8.Db'.
Package restore failed. Rolling back package changes for 'Loqu8.Db'.
========== Finished ==========
Time Elapsed: 00:00:00.8491585
```

Perhaps I am using the wrong version or doing the wrong thing? Any chance
of supporting watchos or tizen?

**Comment by Cheesebaron** [comment]
I think you need to add an import which tells what PCL profile to map. Like @jamesmontemagno describes on his blog: http://motzcod.es/post/148657853472/installing-a-pcl-into-netstandard-libraries

PR's for WatchOS and Tizen are welcome. Currently focusing on MvvmCross 5.0 tasks. Support for those two is not ruled out at all though.

**Comment by tofutim** [comment]
Thanks for the link to the PCL profile. This really is insanity. I think
I'm getting an ulcer.

**Comment by tofutim** [comment]
There is some strange stuff going on there... I tried

  "frameworks": {
    "netstandard1.1": {
      "imports": "portable-net45+netcore45+wpa81"
    }
  }

and MvvmCross only installs, Bindings, Platform, etc. do not show up.

**Comment by martijn00** [comment]
This PR is too messy. I'll work on a new one with the latest changes already in.

**Comment by sidwall** [comment]
When will MvvmCross be portal to .NET Standard?

**Comment by nmilcoff** [comment]
It's planned for v6 @sidwall. Conversation takes place in #2059.

**Pull request closed without merging**
