### PR TITLE
Plugin loading on references of core assemblies

### PR DESCRIPTION
**Pull request by rdorta**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Fixes cases of plugin usage in core assembly with no explicit reference on the entry point assembly.
This makes MvxSetup load all referenced assemblies in the entry point referenced assemblies.
Fixes cases where in WPF as an example, we don't need to have a LinkerPleaseIncludeFile and also have no need to create an instance or static reference to a Plugin.

### :arrow_heading_down: What is the current behavior?
If you use a plugin in a WPF project as an example you have to create a strong reference to a Plugin type so that the plugin assembly can be loaded in AppDomain.

### :new: What is the new behavior (if this is a feature change)?
Now you don't need a strong reference, because you probably already have it in your Core project, so MvxSetup will look for plugins in the core project references as well.

### :boom: Does this PR introduce a breaking change?
No.

### :bug: Recommendations for testing
Running any plugin in all projects without having a strong reference type to any type in plugin assembly.

### :thinking: Checklist before submitting

- [X ] All projects build
- [ X] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [X ] Rebased onto current develop

### CODE REVIEW

**Comment by martijn00** [comment]
This is probably related to https://github.com/MvvmCross/MvvmCross/pull/2844

Can you rebase on 6.1 and check that change?

**Comment by rdorta** [comment]
Did something wrong maybe? I rebased it on 6.1.0 and inherited lots of commits.

**Comment by martijn00** [comment]
@rdorta Yeah you merged instead of rebase it seems. I took a look at rebasing, but got lots of conflicts. I think it might be best to make a new PR with 6.1 as base branch and copy the code changes into that new branch.

**Comment by rdorta** [comment]
k

**Pull request closed without merging**
