### PR TITLE
[WIP] Issue 1465 - Switch to ViewHolder pattern instead of wrapping in FrameLayout for MvxListView items

### PR DESCRIPTION
**Pull request by orzech85**
#1465 

I would like to share my idea to solve this issue. I am going to refactor it (eg. remove MvxListItemView at all) etc. I have used View.Tag for store BindingContext (eg. for RadioButtons). It is probably not the best solution, but in ListView View Holder pattern Tag is used to hold the view...
What do you think about it?

Please notice that I am quite fresh MvvmCross contributor, but I am thirst of knowledge about Mvx :)

### CODE REVIEW

**Comment by kjeremy** [comment]
If you are going to use tags please use a key: https://developer.android.com/reference/android/view/View.html#setTag(int, java.lang.Object).

If you could fix your indentation to match the rest of the files that would make this a little more readable.

FWIF I'm not sure I like storing the binding context in a tag.  Will review more later.

**Comment by orzech85** [comment]
I have used data from Adapter except pass DataContext in Tag. It is similar like in MvxListViewSelectedItemTargetBinding. What do you think about that now?

**Comment by martijn00** [comment]
The only remark i have is to cleanup the lines that you commented out.

**Comment by orzech85** [comment]
Ok. I would like to clean it up at all before merge.

**Comment by orzech85** [comment]
Unfortunatelly I have no idea how to solve that without Tag. In Adapter `convertView` is of type `View`. Only possibility to add some object to view is `Tag`. But it is common for ViewHolder pattern for ListView (https://developer.android.com/training/improving-layouts/smooth-scrolling.html). I have used `Tag` without key, because `SetTag(int, Object)` is significant slower. @kjeremy - if you think despite this I should use `Tag` with key, please let me know. 

This pull request removes unnecessary view nesting from ListView/RadioGroup items. I have tried to implement ItemTemplates like in RecyclerView, but it is a bigger refactoring :) Maybe it should be a subject to another pull request?

**Comment by kjeremy** [comment]
How is using `SetTag` measurably slower?  That sounds odd to me since they both go through JNI.  We also use `SetTag` when inflating views: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Binding/Droid/Views/MvxLayoutInflater.cs#L52

**Comment by orzech85** [comment]
I have read here about that: http://www.jaysoyer.com/2014/12/settag-vs-settag/

> However when using the setTag(int, Object) method, there’s a variable cost.  Remember, internally it stores each View in a SparseArray which uses a binary search for retrieval.  That means for every View stored, you get hit on average with a O(log n) look up. On top of that, you need to type cast every found object.  This is all probably negligible given one or two Views to construct, however as View complexity goes up so will the cost.

**Comment by kjeremy** [comment]
Wow!  I didn't know about that.  Yet one more legitimate reason to hate on Android.  Leave the tag as is then.

**Comment by Cheesebaron** [comment]
Is this ready for testing and review?

**Comment by orzech85** [comment]
I think yes.

**Comment by Cheesebaron** [comment]
Cool, will give it a spin and see what I can find.

**Comment by Cheesebaron** [comment]
Just tested ListView a bit. View Hierarchy looks good. No more wrapping and bindings seems to work OK.

**Comment by Cheesebaron** [comment]
I've verified that https://github.com/MvvmCross/MvvmCross/issues/1451 is fixed in this PR.

This seems good to go.

**Comment by kjeremy** [comment]
Can we  clean up the whitespace before pulling it in?

**Comment by Cheesebaron** [comment]
Whitespace looks OK in XS. Haven't checked in VS.

**Comment by kjeremy** [comment]
The diff on github shows some things misaligned.

**Comment by Cheesebaron** [comment]
Will check it in VS. Probably Tabs vs Spaces territory.

**Pull request merged**
