### PR TITLE
Update Documentation events available

### PR DESCRIPTION
**Pull request by juansturla**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Docs Update

### :arrow_heading_down: What is the current behavior?
The list of available events was outdates

### :new: What is the new behavior (if this is a feature change)?
Now is updated

### :boom: Does this PR introduce a breaking change?
No

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [X] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/MvvmCross/MvvmCross?pullRequest=4273) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/MvvmCross/MvvmCross?pullRequest=4273) before we can accept your contribution.<br/><br/>:x: juansturla [sign now](https://cla.dotnetfoundation.org/MvvmCross/MvvmCross?pullRequest=4273)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/MvvmCross/MvvmCross?pullRequest=4273) it.</sub>

**Comment by Cheesebaron** [comment]
What branch is this based on? Seems to pull in a bunch of other commits.

**Comment by juansturla** [comment]
It was supposed to be branched from develop. Yes, It also caught my attention all those changes
I will check it

**Comment by juansturla** [comment]
@Cheesebaron it looks that when I edited using the github web editor, it created a branch from master :/

**Comment by Cheesebaron** [comment]
Yeah, but that is fine, create from master, and target master.

**Pull request closed without merging**
