### PR TITLE
Use gitlink to inject source references in PDBs back to mvvmcross repo

### LINKED ISSUE #1314: Generate PDBs for source linking with GitLink
[GitLink](https://github.com/GitTools/GitLink) looks like a less error prone way to inject source information into our PDBs.

### PR DESCRIPTION
**Pull request by kjeremy**
This requires the user to have `gitlink.exe` in their `PATH` which is typically installed via `chocolatey`.  See https://github.com/GitTools/GitLink/

Fixes #1314

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Do we really need to remove source files from the nuspecs? Can't this work without removing it as long as we don't generate symbols?

**Comment by kjeremy** [comment]
I believe we do since gitlink writes the references to the source files.
Maybe it's in the gitlink docs. I can check early in the week.

**Comment by Cheesebaron** [comment]
I've been using GitLink it some of my own Xamarin libraries and it simply does not work. I can't step into anything that generates mdb instead of pdb files.

**Comment by martijn00** [comment]
@kjeremy Do we still want this in?

**Comment by Cheesebaron** [comment]
This is part of the CI task. However, this should be done for all packages, and will simply be a step in the build.

**Comment by kjeremy** [comment]
@Cheesebaron does that mean gitlink works for you again?

**Comment by Cheesebaron** [comment]
Uhm, haven't tried it recently. My hunch is that I shouldn't include mdb files and only pdb files. Will try again soon-ish.

**Comment by Cheesebaron** [comment]
We do this in the new CI builds

https://github.com/MvvmCross/MvvmCross/blob/develop/build.cake#L61

**Pull request closed without merging**
