### PR TITLE
Virtualize MvxExpandableListAdapter methods

### PR DESCRIPTION
**Pull request by viniciusmaia**
Please, in futre versions of MvvmCross, change the MvxExpandableListAdapter methods to enable that methods be overwriten, because I had situations that I needed override GetChildView method and had problems.

### CODE REVIEW

**Comment by martijn00** [comment]
It seems that this was done once before by https://github.com/MvvmCross/MvvmCross/commit/3fc1288e3276a4ac989f44d1bfc17f808a782c1f

Was this change lost somehow?

**Comment by martijn00** [comment]
@jamie94bc do you know what to choose here?

**Comment by martijn00** [comment]
After looking into this, it seems good to go. Let's try this and revert if problems come up.

**Comment by jamie94bc** [comment]
I think this once was the case, but was overwritten by another PR. Thanks for merging!

**Comment by viniciusmaia** [comment]
The problem isn't in TableViewCell. Is a problem of MvxExpandableListAdapter of Android.

**Comment by jamie94bc** [comment]
@viniciusmaia can you submit a new PR with the proposed fixes?

**Comment by viniciusmaia** [comment]
Done!

https://github.com/MvvmCross/MvvmCross/pull/1597

**Comment by viniciusmaia** [comment]
Jamie, I created an issue for this times ago.

That's the issue: https://github.com/MvvmCross/MvvmCross/issues/1582

It's a simple change. Just add the keyword virtal MvxExpandableListAdapter methods to allow them be overwritten.

https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Binding/Droid/Views/MvxExpandableListAdapter.cs#L21

**Comment by jamie94bc** [comment]
This is already the case in develop, master and the 4.4 release: https://github.com/MvvmCross/MvvmCross/blob/4.4.0/MvvmCross/Binding/Droid/Views/MvxExpandableListAdapter.cs

4.0 is an old branch.

**Comment by viniciusmaia** [comment]
Ow, thanks!

**Pull request merged**
