### PR TITLE
MvxTapGestureRecognizerBehaviour with CancelsTouchesInView

### PR DESCRIPTION
**Pull request by promontis**
#1303

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Looks good to me

**Comment by promontis** [comment]
Can you see why the build fails?

**Comment by Cheesebaron** [comment]
Yeah it has always done so in the main repo, don't worry. It will be fixed :)

**Comment by promontis** [comment]
Thnx @martijn00 !

**Comment by martijn00** [comment]
Thank you @promontis for contributing!

**Pull request merged**
