### PR TITLE
All asynchronous calls

### PR DESCRIPTION
**Pull request by andrechi1**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

It's getting more asynchronous. And MvvmCross, you have. GetAwaiter(). GetResult();, which cause problems on some platforms. 
This is a proposal for change, so that all calls are asynchronous.
It's unfinished. But I send it, to have your feedback.

### :memo: Links to relevant issues/docs

https://github.com/MvvmCross/MvvmCross/issues/3814#issue-644379944
https://github.com/MvvmCross/MvvmCross/issues/3213#issuecomment-652492077

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
@andrechi1 this work was started by @Cheesebaron a while ago - see https://github.com/MvvmCross/MvvmCross/pull/3222
I know that we all want async throughout the framework but the issue is that most platforms have strict startup policies which don't play nicely with async. The solution is to force the async processing similar to what @Cheesebaron has in his PR.
This PR is massive - I suspect we'll need to carve off parts that can be reviewed and accepted, if possible

**Comment by andrechi1** [comment]
For platforms that do not support asynchronous. They use something similar to

```C#
return new ValueTask();
```
```C#
return Task.CompletedTask;
```
```C#
return Task<bool>.FromResult(true);
```

Do it little by little. It's hard. Asynchronouss have to cover everything flowing.

I think it's better to keep working on this line. And merge when stable.

About #3222. Locks are controlled with ConfigureAwait(false); and ConfigureAwait(true); We have to be very careful. I have to keep working to make everything work out.

**Comment by Cheesebaron** [comment]
This PR needs thorough testing on _all_ platforms to check that startup works correctly.

**Comment by andrechi1** [comment]
Si, es un cambio muy grande. Yo estoy mirando MvxSingleton, y me está causando problemas. Quizás, deberíamos utilizar alguna librería de IoC.

**Comment by nickrandolph** [comment]
@Cheesebaron how close was your PR from being ready? The only way I see this working is with us forcing the async pump, which is what was discussed around your PR a while ago. 
@andrechi1 simply forcing FromResult isn't an option as this will just end up deadlocking developer code that is designed to run asynchronously. The solution in the short term around the MvxSingleton is to just **not** do async stuff during starting.... which ironically is how all the platform startups seem to be designed. I know that this isn't **the** solution but attempting to force async into the startup logic is something we've struggled with for a long time.

**Comment by andrechi1** [comment]
FromResult  should not produce an aa because it is a completed task. FromResul and new ValueTask, is the simple way to emulate an asynchronous interface in synchronous environment. In the future it can be improved.

The starter's working. I'm having mvxSetupSingleton the problem. It  no longer need to use TaskCompletionSource, and I want to simplify it.

An asynchronous start is important. Because it allows you to perform tasks in parallel. And reduce the start-up time.

**Comment by Cheesebaron** [comment]
The async startup in MvvmCross doesn't help _that_ much, most of the time gained is swallowed by the overhead of the async methods anyways. What _really_ makes startup performance is profile AOT.

**Comment by andrechi1** [comment]
Asynchronous methods are highly optimized. And devices have more and more cores. Already a ticket started 20% faster on Android.
What I want is for the app to start while it keeps doing things in the background.

**Comment by andrechi1** [comment]
I close the PR, to send the changes step by step.

**Pull request closed without merging**
