### PR TITLE
Cleanup of code using C#6

### PR DESCRIPTION
**Pull request by martijn00**

### CODE REVIEW

**Comment by kjeremy** [comment]
:+1:

**Comment by promontis** [comment]
The awesomeness :+1:

**Comment by Stephanvs** [comment]
Nothing but :heart:

**Comment by lothrop** [comment]
Having fun with ReSharper? :grinning:

**Comment by lothrop** [comment]
I think we should hold off release of these C# 6 changes in a non-beta until this Mono compiler bugfix has made it to the Xamarin stable release:

https://bugzilla.xamarin.com/show_bug.cgi?id=37080

**Pull request merged**
