### PR TITLE
Fixes to get pack.ps1 to run again.

### PR DESCRIPTION
**Pull request by lothrop**
Made pack.ps1 run again.
Updated nuspecs to beta8.
Remove outdated MvvmCross.Droid.Maps.

### CODE REVIEW

**Comment by lothrop** [comment]
@Cheesebaron, @martijn00: Are we currently not using the Xamarin.Mac nuspecs?

**Comment by martijn00** [comment]
You mean Xamarin.Mac as targetFramework? I didn't knew that exists, but i guess it could be added. I also see MonoAndroid is used and not Xamarin.Android, should that be changed too?

**Comment by lothrop** [comment]
You mean the referenced assembly? I don't know of a Xamarin.Android.dll. Xamarin.Mac.dll and Xamarin.iOS.dll were introduced with the Unified API breaking change. AFAIK no such change was ever done for Android.

**Comment by lothrop** [comment]
Ah, I just got what you were asking. I think we could add the targetFramework for Mac, too. It appears to be `xamarinmac20` for Xamarin.Mac Unified.

What I was asking: There are three nuspecs specifically for Mac. None of them seem to be referenced in pack.ps1. It appears they are not being published?

https://www.nuget.org/packages?q=MvvmCross.HotTuna.Mac.StarterPack

**Comment by lothrop** [comment]
See also #856. I see we haven't followed the blog entry's advice yet. Should I?

**Comment by martijn00** [comment]
@lothrop I think that from the blog would be good to do. I also noticed some of the projects don't get their symbols published, so that needs to be checked as well.

Also the Mac should be added so they will be published.

**Comment by lothrop** [comment]
Might this be the reason?

https://github.com/MvvmCross/MvvmCross/blob/restructure/nuspec/pack.ps1#L15

**Comment by martijn00** [comment]
Hmm, might be. @Cheesebaron would know.

**Comment by Cheesebaron** [comment]
If they are not in the pack.ps1 script, they are not released on NuGet.

**Comment by lothrop** [comment]
Do you know why there are no symbols for those two packages?

https://github.com/MvvmCross/MvvmCross/blob/restructure/nuspec/pack.ps1#L15

**Comment by lothrop** [comment]
Ah, I see, it produces an error message otherwise.

**Pull request merged**
