### PR TITLE
Parametrized app start

### PR DESCRIPTION
**Pull request by sylvain-toptal**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Allows a parametrized app start hint and the possibility to provide the hint from shared code.

### :arrow_heading_down: What is the current behavior?
Non-existent

### :new: What is the new behavior (if this is a feature change)?
Start you app with a parametrized hint without using a custom app start

### :boom: Does this PR introduce a breaking change?
no

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [X] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
A couple of things:
- Can you rebase onto the 6.1 branch 
- Can you provide an example of calling this new app start from one of the playground apps?

**Comment by sylvain-toptal** [comment]
Ewww, rebasing on 6.1 pulls the latest `dev` changes...  I might need some help to do this @nickrandolph , my Git knowledge of Rebase is limited
.

**Comment by nickrandolph** [comment]
@sylvain-toptal try rebasing onto the branch again, this time, use --force when you push. That should clean up the commit history

**Comment by sylvain-toptal** [comment]
Doesn't appear to change a thing

**Comment by sylvain-toptal** [comment]
Would an empty override of the MvxApp `GetAppStartHint` be enough as an example?

**Comment by sylvain-toptal** [comment]
Created a new PR started from branch 6.1 and with the right GH account!
https://github.com/MvvmCross/MvvmCross/pull/2854

**Pull request closed without merging**
