### PR TITLE
Now Forms MasterDetail can launch on iOS

### PR DESCRIPTION
**Pull request by mellson**
Now the Forms MasterDetail example can launch on iOS.
Still not working on Android though...

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix

### :arrow_heading_down: What is the current behavior?
The Forms MasterDetail Example can't launch because of a missing call to Forms.Init()

### :new: What is the new behavior (if this is a feature change)?
Now the example can launch on iOS - but still not Android though...

### :boom: Does this PR introduce a breaking change?
No

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Nuspec files were updated (when applicable)
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by martijn00** [comment]
In the FormsSetup this was done in https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross-Forms/MvvmCross.Forms.iOS/MvxFormsIosSetup.cs#L58 but indeed not called on MasterDetail. I'm wondering if we need to change this a bit so it gets called no matter what presenter you use.

**Comment by mellson** [comment]
I have tried to solve this in a more general way, what do you think?

**Comment by mellson** [comment]
I only tested iOS (which should be ok for this change I guess), with normal and masterdetail presenters.

**Comment by martijn00** [comment]
Aah right, yes, but i think we should probably do something similar in Android and UWP.

**Comment by mellson** [comment]
I have added similar code for Android and UWP. I have tested some of the Android test projects, it's not all of them that can even launch - with or without this change.
I am not able to test the UWP projects. But I don't think this will break anything 🤞

**Comment by martijn00** [comment]
Some of the test projects are a bit broken indeed. Looks good i think, lets see how it goes with this.

**Pull request merged**
