### PR TITLE
Add more Android Target bindings

### PR DESCRIPTION
**Pull request by Cheesebaron**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :new: What is the new behavior (if this is a feature change)?
Added target bindings for

- VideoView Uri
- WebView Uri
- WebView Html Data
- View Focus Change

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Ehm... There was a build error...

**Comment by kmiterror** [comment]
I want to add a comment on issue that some people might face because of this PR. Especially that it's time consuming to figure out.
Before this PR there was no Html binding for WebView in Android. 
We (and probably some more devs) created our own bindable property in a class which inherits from WebView. 
After updating to 6.4.0 we discovered that we have a problem with our webview. 
Apparently this is because of naming collision (we also named our property "Html"), and our property was overriden by this PRs implementation.

It is important to note that LoadData method is not enough in many cases, as you might need to provide base url. We use LoadDataWithBaseURL so we renamed our property to 'CustomHtml' so it doesn't collide with the MvvmCross implmentation.
Perhaps it's matter of discussion but maybe it is worth to add 'baseUrl' as a param when using Html binding?

**Comment by Cheesebaron** [comment]
@kmiterror what do you mean with "add `baseUrl` as a param"? Where would you add that?

**Comment by kmiterror** [comment]
I'm not sure entirely how to solve it.
First thing that comes to me is passing an object instead of string with 2 propeties one for Html and the other for BaseUrl. 
So when calling Html binding you would have to pass well known object, something like:
```
MvxWebViewHtmlParams {
   string Html {get;set;}
   string BaseUrl {get;set;}
}
```

Other possibility  might be to introduce property called BaseUrl and "if not empty" call LoadDataWithBaseURL method instead of LoadData

Basically this is an open question.
I rather wanted to point out a problem that we faced (naming collision) and how we solved it.

**Pull request merged**
