### PR TITLE
Changed Cirrious.MvvmCross.Droid.FullFragging to use API 15

### PR DESCRIPTION
**Pull request by monesprit54**
Project "Cirrious.MvvmCross.Droid.FullFragging" is built on Api Level 14 (4.0) which is marked as obsolete in SDK console.

This should be changed to API Level 15.

### CODE REVIEW

**Comment by kjeremy** [comment]
The samples for API14 are marked obsolete, the SDK is not.  I think we still want to support ICS.

**Comment by monesprit54** [comment]
@kjeremy the SDK is obsolete now. The sdk cannot be downloaded in Windows if you don't choose "obsolete" option in show section.

Attached a captured picture of SDK manager.
screen shot 2015-04-09 at 10 24 24 am

**Comment by monesprit54** [comment]
It is marked as obsolete in OS X as well.

screen shot 2015-04-09 at 10 54 20 am

**Comment by kjeremy** [comment]
Yeah but we support devices running API15.

**Comment by monesprit54** [comment]
This commit changes target api from 14 to 15. Thus, we can still support ICS users.

**Comment by Cheesebaron** [comment]
I see that now. Had to update my SDK before it appeared obsolete.

**Comment by Cheesebaron** [comment]
Can you fix the merge conflicts?

**Comment by monesprit54** [comment]
Pulled latest 3.5 into my branch. Good to go :+1:

**Pull request merged**
