### PR TITLE
Change Tab Aware Behavior

### PR DESCRIPTION
**Pull request by bbenetskyy**
### :arrow_heading_down: What is the current behavior?

If you need to pass data between tabs in runtime you should define your behavior and attach it.

### :new: What is the new behavior (if this is a feature change)?

Now you can use build-in behavior for `MvxTabbedPage`. At ViewModels For that in tabs which should share or get data from others in runtime, we should implement `IMvxChangeTabAware<TParameter>` and add `MvxChangeTabBehavior<TParameter>` with the same `TParameter` to your `MvxTabbedPage`(root page).

### :memo: Links to relevant issues/docs

New Docs are attached to this PR

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [x] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contributing/mvvmcross-docs-style-guide))
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by Cheesebaron** [comment]
This is for Forms only?

**Comment by bbenetskyy** [comment]
@Cheesebaron, in brief - yes. As far as I know, behaviors are mostly used in Xamarin.Forms projects. That's why it was an idea to simplify life just by using the attached behavior to standard `MvxTabbedPage`. 

Is there any easy way to use the attached behaviors for tabbed pages in Xamarin.Android, Xamarin.iOS and other Native projects?

**Comment by Cheesebaron** [comment]
@bbenetskyy this is fine that it is a Forms only thing. I'll have a stab at reviewing it this weekend.

**Comment by bbenetskyy** [comment]
@Cheesebaron thatnks for reviewing! 

The main idea of PR was about passing data not only on first navigation to tab but also at any time when the tab is opened.

I'm not familiar at the moment with `ChangePresentation` and `MvxPagePresentationHint` but suppose that it forces tab to be changed. But is any way to handle that when the user changing the tab by himself?

**Pull request closed without merging**
