### PR TITLE
Android ACW naming

### PR DESCRIPTION
**Pull request by martijn00**
Fixes for #958. Let me know if i missed something.

More information about the naming change: http://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.1/#Android_Callable_Wrapper_Naming

### CODE REVIEW

**Comment by slodge** [comment]
:+1: for the fixes :)

Looking at the links for #958 I'd guess that only things that go in external scripts, axml or in Java need to be set - so I'd agree the adapters aren't needed.

- http://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.1/#Android_Callable_Wrapper_Naming seems to suggest that these are only needed when something accesses the Java equivalent name of a C# class.

Although (actually) given that MvvmCross does the axml inflation for views using the C# namespaces, then I'm not sure we'll hit issues with views either... but it's definitely good to have them safely non-MD5 named :) Thanks :)

**Comment by kjeremy** [comment]
See comment 7 on http://forums.xamarin.com/discussion/37277/beta-release-xamarin-android-5-1-0-new-features-and-bug-fixes for clarification on how this affects axml.

**Comment by kjeremy** [comment]
5.1 is now available as stable.

**Comment by slodge** [comment]
woohoo

**Pull request merged**
