### PR TITLE
revert changes in MvxCollectionViewSource

### PR DESCRIPTION
**Pull request by softlion**
I moved all code related to animating items in a new MvxCollectionViewSourceAnimated class, so existing apps won't be affected.

### CODE REVIEW

**Comment by martijn00** [comment]
I guess this merge won't make any real change, so i've merged it.

**Comment by softlion** [comment]
Well, it will make mvvmcross life easier, as they won't be any regression at all.
For those who wish to use the new animated collection source, they should understand that collection changes are treated asynchronously by iOS, and they should not change the collection before each animated batch is finished (otherwise it will crash ios with a datasource inconsistency exception). The problem lies in the C# event system which is synchronous, and in the ObservableCollection class which can not register batch changes. A good solution would be to mimic the PerformBatchUpdate ios method in ObservableCollection by adding some code which could be called like this:

    using(mycollection.StartBatchUpdate())
    {
        mycollection.RemoveAll();
        mycollection.Add(myitems);
    }

A new ObservableCollection event type would be triggered, containing the list of batch operations, which would be mirrored on the UICollectionView inside a PerformBatchUpdate block.

**Comment by martijn00** [comment]
Hehe, what i ment was, since i merged your other PR this PR won't change anything in the code.

**Comment by tougher** [comment]
It's a little unrelated to this PR but the logic for updating (move, replace) the collection view in MvxCollectionViewSourceAnimated is broken. It took me quite some time to realise this and I want to save others (I don't think there are any, since [this commit](https://github.com/MvvmCross/MvvmCross/commit/10c1731778d7ea425859d72f78d8bf288e36fa8e)) the pain. Should I make a new PR with the fixes?

**Comment by softlion** [comment]
Yes of course.
Note that i am not using this version but this one. But i can't remember why.

```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Threading.Tasks;
using Foundation;
using MvvmCross.Binding.Attributes;
using MvvmCross.Binding.ExtensionMethods;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Platform;
using MvvmCross.Platform.Exceptions;
using MvvmCross.Platform.WeakSubscription;
using UIKit;
using Vapolia.Toolbox.Tools;

namespace Radios.Ios.Views
{
    public class MvxCollectionViewSourceAnimated1 : MvxCollectionViewSource
    {
        private readonly object collectionChangedLock = new object();
        private Task runningChangeTask = Task.FromResult(true);
        private UICollectionView collectionView;

        /// <summary>
        /// UICollectionView animations must be synchronized: the itemsSource content must not change until the animation ends.
        /// As we can not assume that the backing collection is thread safe and waits for us, we keep a copy of its items,
        /// hoping they won't be disposed explicitely before the next UICollectionView animation ends.
        /// The best would be a new NotifyCollectionChangedEventArgs with support for multiple changes, and a new async (awaitable) event for changes.
        /// </summary>
        private IEnumerable itemsSourceBeforeAnimation;

        /// <summary>
        /// When a collectionchanged event is received, if the number of changed items is over MaxAnimatedItems, the collection will not animate changes.
        /// This is a guard to prevent creating a large array of changed indexes, when the collection is large.
        /// </summary>
        public int MaxAnimatedItems { get; set; } = 40;

        public MvxCollectionViewSourceAnimated1(UICollectionView collectionView) : base(collectionView)
        {
            this.collectionView = collectionView;
        }

        public MvxCollectionViewSourceAnimated1(UICollectionView collectionView, NSString defaultCellIdentifier) : base(collectionView, defaultCellIdentifier)
        {
            this.collectionView = collectionView;
        }

        private IDisposable subscription;

        //BeginChange
        [MvxSetToNullAfterBinding]
        public override IEnumerable ItemsSource
        {
            get
            {
                return base.ItemsSource;
            }
            set
            {
                var isSame = base.ItemsSource == value;
                if (!isSame)
                {
                    subscription?.Dispose();
                    subscription = null;
                }
                base.ItemsSource = value;

                var collectionChanged = value as INotifyCollectionChangedEx;
                if (collectionChanged != null)
                {
                    subscription = new MvxWeakEventSubscription<INotifyCollectionChangedEx, EventArgs>(collectionChanged, nameof(collectionChanged.BeginChange), (source,args) =>
                    {
                        itemsSourceBeforeChange = (ItemsSource as IEnumerable<object>)?.ToList();
                    });
                }
            }
        }

        private IEnumerable itemsSourceBeforeChange;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                subscription.Dispose();
                subscription = null;
            }

            base.Dispose(disposing);
        }

        protected override void CollectionChangedOnCollectionChanged(object sender, NotifyCollectionChangedEventArgs args)
        {
            var itemsSource =  (ItemsSource as IEnumerable<object>)?.ToList();
            if (itemsSource == null)
                throw new ArgumentException("ItemsSource must be convertible to IEnumerable<object>, as this code needs to take a snapshot of the list in order to be thread safe for the ios animations");
            var previousItems = itemsSourceBeforeChange;

            lock (collectionChangedLock)
            {
                var existingTask = runningChangeTask;
                runningChangeTask = CollectionChangedOnCollectionChangedAsync(args, existingTask, itemsSource, previousItems);
            }
        }

        protected override object GetItemAt(NSIndexPath indexPath)
        {
            var itemsSource = itemsSourceBeforeAnimation ?? ItemsSource;
            return itemsSource?.ElementAt(indexPath.Row);
        }

        public override nint GetItemsCount(UICollectionView collectionView, nint section)
        {
            var itemsSource = itemsSourceBeforeAnimation ?? ItemsSource;
            return itemsSource?.Count() ?? 0;
        }

        private async Task CollectionChangedOnCollectionChangedAsync(NotifyCollectionChangedEventArgs args, Task existingTask, IEnumerable updatedList, IEnumerable originalList)
        {
#if DEBUG
            var section0Itemcount = collectionView.NumberOfItemsInSection(0);
            Mvx.Trace($"CollectionChanged received action:{args.Action} newItems:{args.NewItems?.Count} oldItems:{args.OldItems?.Count} itemsSourceCount:{updatedList.Count()} realSourceCount:{ItemsSource.Count()} oldIndex:{args.OldStartingIndex} newIndex:{args.NewStartingIndex} section0itemcount:{section0Itemcount}");
#endif
            await existingTask;
#if DEBUG
            Mvx.Trace($"CollectionChanged starting action:{args.Action}");
#endif
            try
            {
                itemsSourceBeforeAnimation = updatedList;

                if (args.NewItems?.Count > MaxAnimatedItems || args.OldItems?.Count > MaxAnimatedItems)
                {
                    //No animation change
#if DEBUG
                    Mvx.Trace("Not animating changes, too much items changed");
#endif
                    itemsSourceBeforeAnimation = originalList;
                    await CollectionView.PerformBatchUpdatesAsync(() => { });
                    itemsSourceBeforeAnimation = null;
                    ReloadData();
                }
                else if (args.Action == NotifyCollectionChangedAction.Move)
                {
                    var oldCount = args.OldItems.Count;
                    var newCount = args.NewItems.Count;
                    if (oldCount != newCount)
                        throw new Exception("Move received, but old and new counts differs");
                    if (oldCount == 1)
                    {
                        await CollectionView.PerformBatchUpdatesAsync(() =>
                        {
                            CollectionView.MoveItem(NSIndexPath.FromRowSection(args.OldStartingIndex, 0), NSIndexPath.FromRowSection(args.NewStartingIndex, 0));
                        });
                    }
                    else
                    {
                        //Does not work with reloaditems (no animation + cell does not rebind)
                        //var indexes = new NSIndexPath[oldCount + newCount];

                        //var startIndex = args.OldStartingIndex;
                        //for (var i = 0; i < oldCount; i++)
                        //    indexes[i] = NSIndexPath.FromRowSection(startIndex + i, 0);
                        //startIndex = args.NewStartingIndex;
                        //for (var i = oldCount; i < oldCount + newCount; i++)
                        //    indexes[i] = NSIndexPath.FromRowSection(startIndex + i, 0);

                        //CollectionView.ReloadItems(indexes);

                        itemsSourceBeforeAnimation = originalList;
                        await CollectionView.PerformBatchUpdatesAsync(() => { });
                        itemsSourceBeforeAnimation = null;
                        ReloadData();
                    }
                }
                else if (args.Action == NotifyCollectionChangedAction.Remove)
                {
                    await CollectionView.PerformBatchUpdatesAsync(() =>
                    {
                        int oldStartingIndex = args.OldStartingIndex;
                        var indexPaths = new NSIndexPath[args.OldItems.Count];
                        for (int index = 0; index < indexPaths.Length; ++index)
                            indexPaths[index] = NSIndexPath.FromRowSection((oldStartingIndex + index), 0);
                        CollectionView.DeleteItems(indexPaths);

                    });
                }
                else if (args.Action == NotifyCollectionChangedAction.Add)
                {
                    await CollectionView.PerformBatchUpdatesAsync(() =>
                    {
                        int newStartingIndex = args.NewStartingIndex;
                        var indexPaths = new NSIndexPath[args.NewItems.Count];
                        for (int index = 0; index < indexPaths.Length; ++index)
                            indexPaths[index] = NSIndexPath.FromRowSection((newStartingIndex + index), 0);
                        CollectionView.InsertItems(indexPaths);
                    });
                }
                else
                {
                    itemsSourceBeforeAnimation = originalList;
                    await CollectionView.PerformBatchUpdatesAsync(() => { });
                    itemsSourceBeforeAnimation = null;
                    ReloadData();
                }
            }
            catch (Exception e)
            {
                Mvx.Error(e.ToLongString());
            }

            itemsSourceBeforeAnimation = null;
#if DEBUG
            Mvx.Trace($"CollectionChanged done action:{args.Action} newItems:{args.NewItems?.Count} oldItems:{args.OldItems?.Count}");
#endif
        }
    }
}

```

**Pull request merged**
