### PR TITLE
Refactoring Setup Singleton 

### PR DESCRIPTION
**Pull request by nickrandolph**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Refactor

### :arrow_heading_down: What is the current behavior?
Only Android uses a setup singleton wrapper

### :new: What is the new behavior (if this is a feature change)?
setup singleton can be reused for all platforms

### :boom: Does this PR introduce a breaking change?
No

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ X ] Rebased onto current develop

### CODE REVIEW

**Comment by nickrandolph** [comment]
@martijn00 I've adjusted the AndroidSetupSingleton so that it inherits from a base that can be used by all platforms. The idea would be to add this to all platforms.

**Comment by martijn00** [comment]
I'm not sure the concept of the `IMvxSplashScreen` belongs in the base SetupSingleton as some platforms don't have this concept or do not enforce it. Other than that this direction looks good to me!

**Comment by martijn00** [comment]
Does this fix: https://github.com/MvvmCross/MvvmCross/issues/1472 ?

**Comment by nickrandolph** [comment]
@martijn00 I've adjusted the name of the IMvxSplashScreen to reflect that it's just a class wanting to register a callback for when setup completes. I'll probably adjust the method names in next commit to reflect this too.
This PR should now fix https://github.com/MvvmCross/MvvmCross/issues/1472

**Comment by nickrandolph** [comment]
Adding in contents of WPF splash screen https://github.com/MvvmCross/MvvmCross/pull/2716
and fixing issue https://github.com/MvvmCross/MvvmCross/issues/2684

**Pull request merged**
