### PR TITLE
Allow user to provide full path in the file plugin

### LINKED ISSUE #1673: MvvmCross.Plugins.File MvxFileStore read using full path
### Steps to reproduce

1. Create `OpenReadFullPath(string fullPath)` method

### Expected behavior
I need to the option to use full path in `MvxFileStore`  instead of always using the default. Now, I only need `OpenRead` to read full path.

### Actual behavior
Now, the plugin always add its default path (base path) to the beginning of supplied path.

### Configuration

**Version:** 4.4

**Platform:** Android

### PR DESCRIPTION
**Pull request by willsb**
Closes #1673

I am using a configuration object instead of adding new methods because we’d basically have to double all the existing methods to provide support for all operations.

I am not running on Windows, so I did not implement UWP (and WPF could use a thorough review, just in case).

### CODE REVIEW

**Comment by willsb** [comment]
Now that I read the proposal on #393, maybe it makes sense to add a `DefaultPath` property on the Configuration object as well, allowing consumers to choose whether or not the default path should be used and also select what the default path is. What do you think?

**Comment by Cheesebaron** [comment]
Would be nice to have it configurable.

Another idea is to maybe call it BasePath instead? Makes more sense as you are appending to it.

**Comment by willsb** [comment]
This is ready for a reviewing and merging, @martijn00 :)

**Comment by willsb** [comment]
@Cheesebaron Can you please check this again now? :)

**Pull request merged**
