### PR TITLE
Making it easier to override default IMvxViewModelTypeFinder implementation

### PR DESCRIPTION
**Pull request by nickrandolph**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature 

### :arrow_heading_down: What is the current behavior?
Currently in order to override the implementation of IMvxViewModelTypeFinder you have to override the entire InitializeViewModelTypeFinder method in each setup for your solution

### :new: What is the new behavior (if this is a feature change)?
Can now simply override CreateViewModelByNameLookup, CreateViewModelByNameRegistry or RegisterViewTypeFinder to change the lookup, registry or finder

### :boom: Does this PR introduce a breaking change?
No

### :memo: Links to relevant issues/docs
N/A

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [ ] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Nuspec files were updated (when applicable)
- [ X ] Rebased onto current develop

### CODE REVIEW

**Comment by martijn00** [comment]
I'm not sure this is a good idea, every sort of view in MvvmCross is Mvx based. This is so we can internally make changes to fix bugs. If we are supporting non mvx views it might even get harder for us to keep up to date with external changes.

What's wrong with leaving it as is?

**Comment by nickrandolph** [comment]
There's just too much friction involved in getting started with MVX with Forms.
I submitted this PR mainly to get the conversation started on this - MVX is currently a chore to work with and we need to reduce the drag on developers wanting to use it.
If there's resistance to removing the dependency on Mvx based application and pages I can revert those changes and just leave the changes to the Setup that allows for it to be overridden easier. Let me know what you think

**Comment by nmilcoff** [comment]
If anything is difficult to override or if anything fails, we should just fix it / improve it / document it.

But other than that I think MvvmCross has always been more of a full framework than something you can just plug in in an app. I'd say that discussion should be moved into a separate issue.

**Comment by nickrandolph** [comment]
@martijn00 @nmilcoff I've reverted the changes concerning MvxApplication and MvxContentPage, leaving on the change that makes it easier to override the default finder.

**Pull request merged**
