### PR TITLE
Fixed GetSizeInBytes() to proper handle memory cache limits for the Images

### PR DESCRIPTION
**Pull request by IlSocio**
Computation for the allocated bytes was overestimated.

### CODE REVIEW

**Comment by jamie94bc** [comment]
LGTM :+1:

**Comment by Cheesebaron** [comment]
`BitmapCompat` should be OK to use. Is Support v4 already referenced in DownloadCache?

**Comment by IlSocio** [comment]
I just added the Support v4 package... but I also had to change the compilation target from API 10 to API 15 because the Support v4 package contains only binaries for the API 15 (v4.0.3)

I also noticed that some other project (eg. CossUI.Droid) is already targeting the API 15, so, I suppose that the API 15 is the lowest API level supported by MVVMCross.

**Comment by martijn00** [comment]
Shouldn't this be added to the support repo if we add v4 t this?

**Comment by Cheesebaron** [comment]
[**@IlSocio**](https://github.com/IlSocio) commented on [Aug 14, 2015, 4:40 PM GMT+2](https://github.com/MvvmCross/MvvmCross/pull/1087#issuecomment-131129566 "2015-08-14T14:40:53Z - Replied by Github Comment Enhancer"):
> I just added the Support v4 package... but I also had to change the compilation target from API 10 to API 15 because the Support v4 package contains only binaries for the API 15 (v4.0.3)
> 
> I also noticed that some other project (eg. CossUI.Droid) is already targeting the API 15, so, I suppose that the API 15 is the lowest API level currently supported by MVVMCross.

You are confusing target API with minimum target. Just because a library is using API 15 as target, does not mean it won't work on lower API levels. As long as you are not using methods which are not supported by API 10.

**Comment by Cheesebaron** [comment]
[**@martijn00**](https://github.com/martijn00) commented on [Aug 14, 2015, 6:24 PM GMT+2](https://github.com/MvvmCross/MvvmCross/pull/1087#issuecomment-131168135 "2015-08-14T16:24:53Z - Replied by Github Comment Enhancer"):
> Shouldn't this be added to the support repo if we add v4 t this?

Download cache is a plugin. I guess you could make it depend on our Support v4 package and add a helper for it in there. I dunno. What do you think the appropriate way would be to do this?

**Comment by martijn00** [comment]
I guess it will only be more confusing if we do a helper. So i think that indeed because it is a plugin we can have a dependency on v4.

**Comment by Cheesebaron** [comment]
I guess we can merge this, although we need to fix the nuspec, so it pulls in Support v4 for DownloadCache on Droid.

**Comment by martijn00** [comment]
Fixed nuspec here: https://github.com/MvvmCross/MvvmCross/blob/4.0/nuspec/MvvmCross.HotTuna.Plugin.DownloadCache.nuspec#L30

**Pull request merged**
