### PR TITLE
Added required android version to successfully compile with latest release

### PR DESCRIPTION
**Pull request by raihaniqbal**
Android project will not compile after updating MvvmCross to release 7.0.0. The fix is linked to [Issue 3955](https://github.com/MvvmCross/MvvmCross/issues/3955).

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/MvvmCross/MvvmCross?pullRequest=3958) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/MvvmCross/MvvmCross?pullRequest=3958) before we can accept your contribution.<br/><br/>:x: raihaniqbal [sign now](https://cla.dotnetfoundation.org/MvvmCross/MvvmCross?pullRequest=3958)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/MvvmCross/MvvmCross?pullRequest=3958) it.</sub>

**Comment by Cheesebaron** [comment]
I don't think this is necessary. This can easily be derived from the NuGet package you are installing.

**Comment by raihaniqbal** [comment]
The Nuget package does not automatically change the target Android version in the project settings - this has to be done manually. If someone is following along the TipCalc tutorial from scratch (as opposed to cloning the repo) using VS 2019, creating a blank Android App project might select **Android 8.0** by default. I was getting compilation errors because the namespaces `MvvmCross.Platforms.Android.Core` and `MvvmCross.Platforms.Android.Views` were not being detected. But when I downgraded MvvmCross to release 6.4.1 I was able to compile successfully. That lead me to think it was an issue with the Android version. To confirm this, I checked out the TipCalc project from the repo and I noticed the Android version was set to 10.0. So to test my theory I changed it to 8.0 and boom I was getting the same compilation errors.

**Comment by Cheesebaron** [comment]
I still don't believe this should be information in the TipCalc tutorial

**Comment by robdrimmie** [comment]
You're welcome to think me 18 kinds of fool, you're likely correct, but if this line were in the TipCalc documentation I'd have saved 10 or so minutes of Googling. 

It's perfectly reasonable to say I should have derived the Q dependancy from the NuGet package but I'm moderately new to this tech stack (C#, Xamarin, MvvmCross and definitely NuGet) and it's all quite a lot to take in. I'm not working from the assumption that Microsoft has defaulted me two versions back, and when I see errors in the code I copy and pasted from these instructions I certainly don't attribute them to Microsoft either. 

For whatever weight the opinion of a fairly new user trying to learn your tool is, this inclusion would have been pretty great.

**Comment by raihaniqbal** [comment]
> 
> 
> I'd have saved 10 or so minutes of Googling.

I'm in the same boat as you but you're lucky it only took you 10 minutes to figure it out whereas it took me a while. For the benefit of those who might face the same problem, I posted in Stackoverflow about this and referenced this PR so that eventually Google will pick it up.

**Comment by robdrimmie** [comment]
@raihaniqbal to clarify, it took me 10 minutes of Googling to find this PR. Reading the change you submitted is literally how I got past the problem, which is why I think it would be a valuable addition to the docs.

**Pull request closed without merging**
