### PR TITLE
Add possibility to pass custom objects with Viewmodel navigation

### PR DESCRIPTION
**Pull request by martijn00**
Inspiration from: http://stackoverflow.com/a/29471996/4222823

### CODE REVIEW

**Comment by benhysell** [comment]
That would be nice to have...I've been doing the same thing by hand and it seems to work fine.

**Comment by SeeD-Seifer** [comment]
In short - current implementation is freezy for more then simple objects

In depth. Once upon a time, I had to send non-simple objects between ViewModels. Simple Serialization/Deserialization appeared freeze screen transition a lot on Android devices (for example Nexus 4) and old iOS devices (iPhone 4/4s).

There was few steps on improvement to make object transition smooth.
**Idea:**
1. Store keys to the MvxBundle synchronously.
2. Pass MvxBundle to the ShowViewModel
3. In a new thread serialize objects by keys
4. In the opened ViewModel, await for values by keys

**Concerns:**
Key-value pairs stored to the local DB.
Ensure key-value pairs stored for enough time, to be able reload it when screen restored from tombstone.
Awaiting for object serialisation is not precise for non-nullable types

This is my current implementation which is ugly, but could be used as an example: 
https://gist.github.com/SeeD-Seifer/0df2dfbbe55252fa6d2883b348d0ec68

Didn't expect to share the code, please let me know if it requires more comments around and clean up.

If it appears that this is an overkill and there is more simple solution, I will gladly kill the code and use new approach :)

**Comment by martijn00** [comment]
@SeeD-Seifer i see your concerns, but i think the solution should be more simple to use, like my implementation. Could we somehow mix those two, to make a high performant navigations with parameters?

**Comment by SeeD-Seifer** [comment]
I'm completely agree that solution should be simple, I just didn't find that way yet.

Current implementation cons:
- Serialisation could be heavy
- Only one parameter supported (which means either we can pass one model or create special container per ViewModel transition)

Possible optimisations:
- Make deserialisation asynchronous

**Comment by martijn00** [comment]
The current `IMvxJsonConverter` doesn't have asynchronous support so we shoud add that first i guess.

**Comment by Cheesebaron** [comment]
About async support I think you should read https://github.com/JamesNK/Newtonsoft.Json/issues/66. I think it should be up to the user or the part of the code that requires async deserialization to offload it to a new Task, instead of providing it in MvvmCross.

**Comment by SeeD-Seifer** [comment]
@Cheesebaron good point, thanks. In that case we can only warn developer that he should be careful transferring large objects cos they freeze the app on transition.

**Comment by benhysell** [comment]
Maybe this would be better off as a 'how to' instead of embedding it in the framework because of the risks.  I can already see the issues "I have a giant 5 mb object, why is my screen freezing"

**Comment by Cheesebaron** [comment]
If you are passing around a 5mb object you are already doing it wrong!

**Comment by willsb** [comment]
Awesome proposal, but won't it fall on same the problems mentioned by @roubachof on #1136?

**Comment by SeeD-Seifer** [comment]
How to measure when _dev_ crossed an object limit size? Is 1KB too much? 10KB? 100KB?
If there is a method that could be used wrong, it will be used so.

**Comment by martijn00** [comment]
I've added a description to make the concerns a bit clear to developers. I'll merge this for now, but feel free to open a new PR to improve this. Thanks for all the suggestions and feedback!

**Pull request merged**
