### PR TITLE
Add doc about linking

### PR DESCRIPTION
**Pull request by Cheesebaron**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
docs

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/MvvmCross/MvvmCross#code-style-guidelines))
- [x] Relevant documentation was updated ([docs style guide](https://www.mvvmcross.com/documentation/contribute/mvvmcross-docs-style-guide))
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by nmilcoff** [comment]
Would "skipping assemblies" be a third option we should add here?

**Comment by Cheesebaron** [comment]
@nmilcoff I could add that, but in general skipping MvvmCross entirely is no fun 😄

**Comment by nmilcoff** [comment]
I'd say we include it as a last-resource option, since dealing with the linker in "link-all" mode normally takes some time and effort 😬

**Comment by Cheesebaron** [comment]
@nmilcoff sure, I'll add it to the doc :)

**Comment by kjeremy** [comment]
Do you have any special notes regarding Proguard on Android?  I've run into weird issues in the past and had to disable Multidex/Proguard to get things to work.

**Comment by Cheesebaron** [comment]
@kjeremy special notes, no. Just regular stuff that I could add. Most of the time it just works.

**Pull request merged**
